//go:build go1.22

// Package agentapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260404004943-9ea3cc79a4c7 DO NOT EDIT.
package agentapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AgentStreamContentRole.
const (
	Model AgentStreamContentRole = "model"
	User  AgentStreamContentRole = "user"
)

// Valid indicates whether the value is a known member of the AgentStreamContentRole enum.
func (e AgentStreamContentRole) Valid() bool {
	switch e {
	case Model:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatusEventStatus.
const (
	Active SessionStatusEventStatus = "active"
	Idle   SessionStatusEventStatus = "idle"
)

// Valid indicates whether the value is a known member of the SessionStatusEventStatus enum.
func (e SessionStatusEventStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Idle:
		return true
	default:
		return false
	}
}

// AgentProfileExecutionSettings Runtime-owned execution defaults for an agent profile.
type AgentProfileExecutionSettings struct {
	// DefaultModel Fully-qualified default model in `provider/model-name` form.
	DefaultModel string `json:"defaultModel"`
}

// AgentProfileListResponse List of saved agent profiles.
type AgentProfileListResponse struct {
	Profiles []AgentProfileResponse `json:"profiles"`
}

// AgentProfileResponse A saved agent profile as returned by the API.
type AgentProfileResponse struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"createdAt"`

	// DisplayName Human-friendly profile label (may be empty).
	DisplayName string `json:"displayName"`

	// ExecutionSettings Runtime-owned execution defaults for an agent profile.
	ExecutionSettings AgentProfileExecutionSettings `json:"executionSettings"`

	// Instructions Profile-specific behavior instructions.
	Instructions string `json:"instructions"`

	// Name Unique technical profile name (primary key).
	Name string `json:"name"`

	// Role Profile role describing high-level responsibility.
	Role string `json:"role"`

	// ToolRefs Tool references available to this profile.
	ToolRefs []string `json:"toolRefs"`

	// UpdatedAt ISO 8601 last-update timestamp.
	UpdatedAt time.Time `json:"updatedAt"`
}

// AgentRunRequest defines model for AgentRunRequest.
type AgentRunRequest struct {
	// Message User message for `POST /agent-runs` / continue run: text parts (always user role; not sent by clients).
	Message UserMessageContent `json:"message"`

	// Model Optional model name; empty selects the runtime default (`NewAgentRunnerParams.ModelName`).
	Model *string `json:"model,omitempty"`
}

// AgentStreamContent Model output body on streamed `agent` events: text parts and optional `role` (mapped from ADK session events).
// `parts` may be empty when only metadata is present.
type AgentStreamContent struct {
	// Parts May be empty when only metadata is present; omitting `content` entirely is allowed when there is no body.
	Parts []AgentStreamPart `json:"parts"`

	// Role Producer of the message; may be omitted when not set on the underlying event.
	Role *AgentStreamContentRole `json:"role,omitempty"`
}

// AgentStreamContentRole Producer of the message; may be omitted when not set on the underlying event.
type AgentStreamContentRole string

// AgentStreamEvent Carries a slice of ADK `session.Event` / `model.LLMResponse` fields relevant to clients
// (text streaming, partial chunks, completion). Servers may add optional ids or metadata.
type AgentStreamEvent struct {
	Author *string `json:"author,omitempty"`
	Branch *string `json:"branch,omitempty"`

	// Content Model output body on streamed `agent` events: text parts and optional `role` (mapped from ADK session events).
	// `parts` may be empty when only metadata is present.
	Content *AgentStreamContent `json:"content,omitempty"`

	// ErrorCode Present when the agent surfaced an error on the ADK session event / LLM response.
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	Event        string  `json:"event"`
	Id           *string `json:"id,omitempty"`
	Interrupted  *bool   `json:"interrupted,omitempty"`
	InvocationId *string `json:"invocationId,omitempty"`

	// Partial Incremental model output; when false and `turnComplete` is true, chunk is final for the turn.
	Partial              *bool                  `json:"partial,omitempty"`
	TurnComplete         *bool                  `json:"turnComplete,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// AgentStreamPart A segment in streamed agent output. Exactly one of text, toolCall, or toolResult is present.
type AgentStreamPart struct {
	Text *string `json:"text,omitempty"`

	// ToolCall Tool invocation requested by the model.
	ToolCall *ToolCallData `json:"toolCall,omitempty"`

	// ToolResult Result returned by a tool invocation.
	ToolResult *ToolResultData `json:"toolResult,omitempty"`
}

// CreateAgentProfileRequest Request body for creating a saved agent profile.
type CreateAgentProfileRequest struct {
	// DisplayName Optional human-friendly profile label.
	DisplayName *string `json:"displayName,omitempty"`

	// ExecutionSettings Runtime-owned execution defaults for an agent profile.
	ExecutionSettings AgentProfileExecutionSettings `json:"executionSettings"`

	// Instructions Profile-specific behavior instructions.
	Instructions string `json:"instructions"`

	// Name Unique technical profile name (primary key). Immutable after creation.
	Name string `json:"name"`

	// Role Profile role describing high-level responsibility.
	Role string `json:"role"`

	// ToolRefs Tool references available to this profile.
	ToolRefs *[]string `json:"toolRefs,omitempty"`
}

// CreateProviderRequest Request body for creating a new provider configuration.
type CreateProviderRequest struct {
	// ApiKey API key for authentication. Stored in plaintext (local/dev use).
	ApiKey string `json:"apiKey"`

	// BaseUrl Base URL of the provider API endpoint.
	BaseUrl string `json:"baseUrl"`

	// DisplayName Optional human-friendly label.
	DisplayName *string `json:"displayName,omitempty"`

	// Models Models available through this provider.
	Models *[]ModelConfig `json:"models,omitempty"`

	// Name Unique technical name (primary key). Must match `^[a-z][a-z0-9-]*$`. Immutable after creation.
	Name string `json:"name"`

	// Type Provider protocol type. Only `openai-compatible` is supported. Immutable after creation.
	Type string `json:"type"`
}

// DoneEvent defines model for DoneEvent.
type DoneEvent struct {
	Event string `json:"event"`
}

// ModelConfig A model available through a provider.
type ModelConfig struct {
	// DisplayName Optional human-friendly label (e.g., "GPT 4.1").
	DisplayName *string `json:"displayName,omitempty"`

	// Name Technical model identifier (e.g., "gpt-4.1").
	Name string `json:"name"`

	// Summarization Designates this model for summarization tasks (e.g. generating session titles). If multiple models have this enabled, the first one found is used.
	Summarization *bool `json:"summarization,omitempty"`
}

// ModelInfo A model available across providers, including the provider name for fully-qualified identification.
type ModelInfo struct {
	// DisplayName Optional human-friendly label.
	DisplayName *string `json:"displayName,omitempty"`

	// Name Technical model identifier (e.g., "gpt-4.1").
	Name string `json:"name"`

	// Provider Provider name (prefix in fully-qualified model names like `provider/model-name`).
	Provider string `json:"provider"`
}

// ModelListResponse List of available models across all providers.
type ModelListResponse struct {
	Models []ModelInfo `json:"models"`
}

// ProblemDetails RFC 9457 problem details (subset).
type ProblemDetails struct {
	Detail               *string                `json:"detail,omitempty"`
	Instance             *string                `json:"instance,omitempty"`
	Status               *int                   `json:"status,omitempty"`
	Title                *string                `json:"title,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ProviderListResponse List of provider configurations.
type ProviderListResponse struct {
	Providers []ProviderResponse `json:"providers"`
}

// ProviderResponse A provider configuration as returned by the API (API key is masked).
type ProviderResponse struct {
	// ApiKeyPreview Masked API key preview (e.g. `...xYz1`). Never the full key.
	ApiKeyPreview string `json:"apiKeyPreview"`

	// BaseUrl Base URL of the provider API endpoint.
	BaseUrl string `json:"baseUrl"`

	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"createdAt"`

	// DisplayName Human-friendly label (may be empty).
	DisplayName *string `json:"displayName,omitempty"`

	// Models Models available through this provider.
	Models []ModelConfig `json:"models"`

	// Name Unique technical name (primary key).
	Name string `json:"name"`

	// Type Provider protocol type.
	Type string `json:"type"`

	// UpdatedAt ISO 8601 last-update timestamp.
	UpdatedAt time.Time `json:"updatedAt"`
}

// SessionBoundEvent defines model for SessionBoundEvent.
type SessionBoundEvent struct {
	Event string `json:"event"`

	// SessionId Use this id for `POST /sessions/{sessionId}/agent-runs`.
	SessionId string `json:"sessionId"`
}

// SessionListResponse defines model for SessionListResponse.
type SessionListResponse struct {
	Sessions []SessionMetadata `json:"sessions"`

	// Total Total number of sessions matching the query (before limit/offset).
	Total int `json:"total"`
}

// SessionMetadata defines model for SessionMetadata.
type SessionMetadata struct {
	CreatedAt time.Time `json:"createdAt"`
	SessionId string    `json:"sessionId"`

	// Title Session title. Always non-empty — resolved by the backend. Generated via LLM summarization (if a summarization model is designated), derived from the first user message, or a date-based fallback for sessions without a stored title.
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// SessionStatusEvent defines model for SessionStatusEvent.
type SessionStatusEvent struct {
	Event string `json:"event"`

	// Status Whether a run is currently in progress for this session.
	Status SessionStatusEventStatus `json:"status"`
}

// SessionStatusEventStatus Whether a run is currently in progress for this session.
type SessionStatusEventStatus string

// StreamErrorEvent defines model for StreamErrorEvent.
type StreamErrorEvent struct {
	Code  *string `json:"code,omitempty"`
	Event string  `json:"event"`

	// Message Human-readable failure; after this, the stream may end.
	Message string `json:"message"`
}

// StreamEvent defines model for StreamEvent.
type StreamEvent struct {
	union json.RawMessage
}

// ToolCallData Tool invocation requested by the model.
type ToolCallData struct {
	// Args Arguments passed to the tool (JSON object).
	Args *map[string]interface{} `json:"args,omitempty"`

	// Id Unique call ID matching the tool result.
	Id string `json:"id"`

	// Name Tool function name.
	Name string `json:"name"`
}

// ToolResultData Result returned by a tool invocation.
type ToolResultData struct {
	// Id Call ID matching the original tool call.
	Id string `json:"id"`

	// Name Tool function name.
	Name string `json:"name"`

	// Response Tool output (JSON object).
	Response *map[string]interface{} `json:"response,omitempty"`
}

// UpdateAgentProfileRequest Request body for updating a saved agent profile. `name` is immutable and not accepted here.
type UpdateAgentProfileRequest struct {
	// DisplayName Human-friendly profile label.
	DisplayName *string `json:"displayName,omitempty"`

	// ExecutionSettings Runtime-owned execution defaults for an agent profile.
	ExecutionSettings AgentProfileExecutionSettings `json:"executionSettings"`

	// Instructions Profile-specific behavior instructions.
	Instructions string `json:"instructions"`

	// Role Profile role describing high-level responsibility.
	Role string `json:"role"`

	// ToolRefs Tool references available to this profile. Replaces the existing list.
	ToolRefs *[]string `json:"toolRefs,omitempty"`
}

// UpdateProviderRequest Request body for updating a provider configuration. `name` and `type` are immutable and not accepted here.
type UpdateProviderRequest struct {
	// ApiKey API key for authentication. Omit to keep the current value.
	ApiKey *string `json:"apiKey,omitempty"`

	// BaseUrl Base URL of the provider API endpoint.
	BaseUrl string `json:"baseUrl"`

	// DisplayName Human-friendly label.
	DisplayName *string `json:"displayName,omitempty"`

	// Models Models available through this provider. Replaces the existing list.
	Models *[]ModelConfig `json:"models,omitempty"`
}

// UserMessageContent User message for `POST /agent-runs` / continue run: text parts (always user role; not sent by clients).
type UserMessageContent struct {
	// Parts Must contain at least one segment with non-empty text after server-side validation; empty lists are rejected for POST bodies.
	Parts []UserMessagePart `json:"parts"`
}

// UserMessagePart Single text segment in a user message (request body).
type UserMessagePart struct {
	Text string `json:"text"`
}

// ProfileName defines model for ProfileName.
type ProfileName = string

// ProviderName defines model for ProviderName.
type ProviderName = string

// SessionId defines model for SessionId.
type SessionId = string

// BadRequest RFC 9457 problem details (subset).
type BadRequest = ProblemDetails

// Conflict RFC 9457 problem details (subset).
type Conflict = ProblemDetails

// InternalError RFC 9457 problem details (subset).
type InternalError = ProblemDetails

// NotFound RFC 9457 problem details (subset).
type NotFound = ProblemDetails

// Unauthorized RFC 9457 problem details (subset).
type Unauthorized = ProblemDetails

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	// Limit Maximum number of sessions to return (1–100).
	Limit int `form:"limit" json:"limit"`

	// Offset Number of sessions to skip (for pagination). Defaults to 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateAgentProfileJSONRequestBody defines body for CreateAgentProfile for application/json ContentType.
type CreateAgentProfileJSONRequestBody = CreateAgentProfileRequest

// UpdateAgentProfileJSONRequestBody defines body for UpdateAgentProfile for application/json ContentType.
type UpdateAgentProfileJSONRequestBody = UpdateAgentProfileRequest

// StartAgentRunJSONRequestBody defines body for StartAgentRun for application/json ContentType.
type StartAgentRunJSONRequestBody = AgentRunRequest

// CreateProviderJSONRequestBody defines body for CreateProvider for application/json ContentType.
type CreateProviderJSONRequestBody = CreateProviderRequest

// UpdateProviderJSONRequestBody defines body for UpdateProvider for application/json ContentType.
type UpdateProviderJSONRequestBody = UpdateProviderRequest

// ContinueAgentRunJSONRequestBody defines body for ContinueAgentRun for application/json ContentType.
type ContinueAgentRunJSONRequestBody = AgentRunRequest

// Getter for additional properties for AgentStreamEvent. Returns the specified
// element and whether it was found
func (a AgentStreamEvent) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AgentStreamEvent
func (a *AgentStreamEvent) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AgentStreamEvent to handle AdditionalProperties
func (a *AgentStreamEvent) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["author"]; found {
		err = json.Unmarshal(raw, &a.Author)
		if err != nil {
			return fmt.Errorf("error reading 'author': %w", err)
		}
		delete(object, "author")
	}

	if raw, found := object["branch"]; found {
		err = json.Unmarshal(raw, &a.Branch)
		if err != nil {
			return fmt.Errorf("error reading 'branch': %w", err)
		}
		delete(object, "branch")
	}

	if raw, found := object["content"]; found {
		err = json.Unmarshal(raw, &a.Content)
		if err != nil {
			return fmt.Errorf("error reading 'content': %w", err)
		}
		delete(object, "content")
	}

	if raw, found := object["errorCode"]; found {
		err = json.Unmarshal(raw, &a.ErrorCode)
		if err != nil {
			return fmt.Errorf("error reading 'errorCode': %w", err)
		}
		delete(object, "errorCode")
	}

	if raw, found := object["errorMessage"]; found {
		err = json.Unmarshal(raw, &a.ErrorMessage)
		if err != nil {
			return fmt.Errorf("error reading 'errorMessage': %w", err)
		}
		delete(object, "errorMessage")
	}

	if raw, found := object["event"]; found {
		err = json.Unmarshal(raw, &a.Event)
		if err != nil {
			return fmt.Errorf("error reading 'event': %w", err)
		}
		delete(object, "event")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["interrupted"]; found {
		err = json.Unmarshal(raw, &a.Interrupted)
		if err != nil {
			return fmt.Errorf("error reading 'interrupted': %w", err)
		}
		delete(object, "interrupted")
	}

	if raw, found := object["invocationId"]; found {
		err = json.Unmarshal(raw, &a.InvocationId)
		if err != nil {
			return fmt.Errorf("error reading 'invocationId': %w", err)
		}
		delete(object, "invocationId")
	}

	if raw, found := object["partial"]; found {
		err = json.Unmarshal(raw, &a.Partial)
		if err != nil {
			return fmt.Errorf("error reading 'partial': %w", err)
		}
		delete(object, "partial")
	}

	if raw, found := object["turnComplete"]; found {
		err = json.Unmarshal(raw, &a.TurnComplete)
		if err != nil {
			return fmt.Errorf("error reading 'turnComplete': %w", err)
		}
		delete(object, "turnComplete")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AgentStreamEvent to handle AdditionalProperties
func (a AgentStreamEvent) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Author != nil {
		object["author"], err = json.Marshal(a.Author)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'author': %w", err)
		}
	}

	if a.Branch != nil {
		object["branch"], err = json.Marshal(a.Branch)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'branch': %w", err)
		}
	}

	if a.Content != nil {
		object["content"], err = json.Marshal(a.Content)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'content': %w", err)
		}
	}

	if a.ErrorCode != nil {
		object["errorCode"], err = json.Marshal(a.ErrorCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'errorCode': %w", err)
		}
	}

	if a.ErrorMessage != nil {
		object["errorMessage"], err = json.Marshal(a.ErrorMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'errorMessage': %w", err)
		}
	}

	object["event"], err = json.Marshal(a.Event)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'event': %w", err)
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Interrupted != nil {
		object["interrupted"], err = json.Marshal(a.Interrupted)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'interrupted': %w", err)
		}
	}

	if a.InvocationId != nil {
		object["invocationId"], err = json.Marshal(a.InvocationId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'invocationId': %w", err)
		}
	}

	if a.Partial != nil {
		object["partial"], err = json.Marshal(a.Partial)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'partial': %w", err)
		}
	}

	if a.TurnComplete != nil {
		object["turnComplete"], err = json.Marshal(a.TurnComplete)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'turnComplete': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ProblemDetails. Returns the specified
// element and whether it was found
func (a ProblemDetails) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemDetails
func (a *ProblemDetails) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a *ProblemDetails) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a ProblemDetails) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsSessionBoundEvent returns the union data inside the StreamEvent as a SessionBoundEvent
func (t StreamEvent) AsSessionBoundEvent() (SessionBoundEvent, error) {
	var body SessionBoundEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSessionBoundEvent overwrites any union data inside the StreamEvent as the provided SessionBoundEvent
func (t *StreamEvent) FromSessionBoundEvent(v SessionBoundEvent) error {
	v.Event = "sessionBound"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSessionBoundEvent performs a merge with any union data inside the StreamEvent, using the provided SessionBoundEvent
func (t *StreamEvent) MergeSessionBoundEvent(v SessionBoundEvent) error {
	v.Event = "sessionBound"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSessionStatusEvent returns the union data inside the StreamEvent as a SessionStatusEvent
func (t StreamEvent) AsSessionStatusEvent() (SessionStatusEvent, error) {
	var body SessionStatusEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSessionStatusEvent overwrites any union data inside the StreamEvent as the provided SessionStatusEvent
func (t *StreamEvent) FromSessionStatusEvent(v SessionStatusEvent) error {
	v.Event = "sessionStatus"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSessionStatusEvent performs a merge with any union data inside the StreamEvent, using the provided SessionStatusEvent
func (t *StreamEvent) MergeSessionStatusEvent(v SessionStatusEvent) error {
	v.Event = "sessionStatus"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAgentStreamEvent returns the union data inside the StreamEvent as a AgentStreamEvent
func (t StreamEvent) AsAgentStreamEvent() (AgentStreamEvent, error) {
	var body AgentStreamEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentStreamEvent overwrites any union data inside the StreamEvent as the provided AgentStreamEvent
func (t *StreamEvent) FromAgentStreamEvent(v AgentStreamEvent) error {
	v.Event = "agent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentStreamEvent performs a merge with any union data inside the StreamEvent, using the provided AgentStreamEvent
func (t *StreamEvent) MergeAgentStreamEvent(v AgentStreamEvent) error {
	v.Event = "agent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStreamErrorEvent returns the union data inside the StreamEvent as a StreamErrorEvent
func (t StreamEvent) AsStreamErrorEvent() (StreamErrorEvent, error) {
	var body StreamErrorEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreamErrorEvent overwrites any union data inside the StreamEvent as the provided StreamErrorEvent
func (t *StreamEvent) FromStreamErrorEvent(v StreamErrorEvent) error {
	v.Event = "error"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStreamErrorEvent performs a merge with any union data inside the StreamEvent, using the provided StreamErrorEvent
func (t *StreamEvent) MergeStreamErrorEvent(v StreamErrorEvent) error {
	v.Event = "error"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDoneEvent returns the union data inside the StreamEvent as a DoneEvent
func (t StreamEvent) AsDoneEvent() (DoneEvent, error) {
	var body DoneEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDoneEvent overwrites any union data inside the StreamEvent as the provided DoneEvent
func (t *StreamEvent) FromDoneEvent(v DoneEvent) error {
	v.Event = "done"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDoneEvent performs a merge with any union data inside the StreamEvent, using the provided DoneEvent
func (t *StreamEvent) MergeDoneEvent(v DoneEvent) error {
	v.Event = "done"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StreamEvent) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"event"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t StreamEvent) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "agent":
		return t.AsAgentStreamEvent()
	case "done":
		return t.AsDoneEvent()
	case "error":
		return t.AsStreamErrorEvent()
	case "sessionBound":
		return t.AsSessionBoundEvent()
	case "sessionStatus":
		return t.AsSessionStatusEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t StreamEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StreamEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all saved agent profiles
	// (GET /agent-profiles)
	ListAgentProfiles(w http.ResponseWriter, r *http.Request)
	// Create a new saved agent profile
	// (POST /agent-profiles)
	CreateAgentProfile(w http.ResponseWriter, r *http.Request)
	// Delete a saved agent profile by name
	// (DELETE /agent-profiles/{profileName})
	DeleteAgentProfile(w http.ResponseWriter, r *http.Request, profileName ProfileName)
	// Get a saved agent profile by name
	// (GET /agent-profiles/{profileName})
	GetAgentProfile(w http.ResponseWriter, r *http.Request, profileName ProfileName)
	// Update mutable fields for a saved agent profile
	// (PUT /agent-profiles/{profileName})
	UpdateAgentProfile(w http.ResponseWriter, r *http.Request, profileName ProfileName)
	// Start a new agent run
	// (POST /agent-runs)
	StartAgentRun(w http.ResponseWriter, r *http.Request)
	// List all available models across all providers
	// (GET /models)
	ListModels(w http.ResponseWriter, r *http.Request)
	// List all provider configurations
	// (GET /providers)
	ListProviders(w http.ResponseWriter, r *http.Request)
	// Create a new provider configuration
	// (POST /providers)
	CreateProvider(w http.ResponseWriter, r *http.Request)
	// Delete a provider configuration by name
	// (DELETE /providers/{providerName})
	DeleteProvider(w http.ResponseWriter, r *http.Request, providerName ProviderName)
	// Get a provider configuration by name
	// (GET /providers/{providerName})
	GetProvider(w http.ResponseWriter, r *http.Request, providerName ProviderName)
	// Update a provider configuration by name
	// (PUT /providers/{providerName})
	UpdateProvider(w http.ResponseWriter, r *http.Request, providerName ProviderName)
	// List sessions for the authenticated user
	// (GET /sessions)
	ListSessions(w http.ResponseWriter, r *http.Request, params ListSessionsParams)
	// Read session events (replay history and optionally tail live run)
	// (GET /sessions/{sessionId})
	ReadSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Continue an agent run for an existing session
	// (POST /sessions/{sessionId}/agent-runs)
	ContinueAgentRun(w http.ResponseWriter, r *http.Request, sessionId SessionId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAgentProfiles operation middleware
func (siw *ServerInterfaceWrapper) ListAgentProfiles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgentProfiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAgentProfile operation middleware
func (siw *ServerInterfaceWrapper) CreateAgentProfile(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAgentProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAgentProfile operation middleware
func (siw *ServerInterfaceWrapper) DeleteAgentProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "profileName" -------------
	var profileName ProfileName

	err = runtime.BindStyledParameterWithOptions("simple", "profileName", r.PathValue("profileName"), &profileName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAgentProfile(w, r, profileName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgentProfile operation middleware
func (siw *ServerInterfaceWrapper) GetAgentProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "profileName" -------------
	var profileName ProfileName

	err = runtime.BindStyledParameterWithOptions("simple", "profileName", r.PathValue("profileName"), &profileName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentProfile(w, r, profileName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAgentProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateAgentProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "profileName" -------------
	var profileName ProfileName

	err = runtime.BindStyledParameterWithOptions("simple", "profileName", r.PathValue("profileName"), &profileName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAgentProfile(w, r, profileName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartAgentRun operation middleware
func (siw *ServerInterfaceWrapper) StartAgentRun(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartAgentRun(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProviders operation middleware
func (siw *ServerInterfaceWrapper) ListProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProvider operation middleware
func (siw *ServerInterfaceWrapper) CreateProvider(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProvider(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProvider operation middleware
func (siw *ServerInterfaceWrapper) DeleteProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "providerName" -------------
	var providerName ProviderName

	err = runtime.BindStyledParameterWithOptions("simple", "providerName", r.PathValue("providerName"), &providerName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProvider(w, r, providerName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProvider operation middleware
func (siw *ServerInterfaceWrapper) GetProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "providerName" -------------
	var providerName ProviderName

	err = runtime.BindStyledParameterWithOptions("simple", "providerName", r.PathValue("providerName"), &providerName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProvider(w, r, providerName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProvider operation middleware
func (siw *ServerInterfaceWrapper) UpdateProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "providerName" -------------
	var providerName ProviderName

	err = runtime.BindStyledParameterWithOptions("simple", "providerName", r.PathValue("providerName"), &providerName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProvider(w, r, providerName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSessionsParams

	// ------------- Required query parameter "limit" -------------

	if paramValue := r.URL.Query().Get("limit"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReadSession operation middleware
func (siw *ServerInterfaceWrapper) ReadSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReadSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ContinueAgentRun operation middleware
func (siw *ServerInterfaceWrapper) ContinueAgentRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ContinueAgentRun(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/agent-profiles", wrapper.ListAgentProfiles)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/agent-profiles", wrapper.CreateAgentProfile)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/agent-profiles/{profileName}", wrapper.DeleteAgentProfile)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/agent-profiles/{profileName}", wrapper.GetAgentProfile)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/agent-profiles/{profileName}", wrapper.UpdateAgentProfile)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/agent-runs", wrapper.StartAgentRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/models", wrapper.ListModels)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/providers", wrapper.ListProviders)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/providers", wrapper.CreateProvider)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/providers/{providerName}", wrapper.DeleteProvider)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/providers/{providerName}", wrapper.GetProvider)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/providers/{providerName}", wrapper.UpdateProvider)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions", wrapper.ListSessions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/{sessionId}", wrapper.ReadSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions/{sessionId}/agent-runs", wrapper.ContinueAgentRun)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x963Ibt5L/q6Dmf6r+lJekpBw5J5FqPziyk2jji0q0ams39BahmSaJeAaYABjKjItV",
	"eYc9X/b18iRb3cDcODO86GLH5+wXl0jOAI3Grxt9hT8GoUpSJUFaE5x+DFKueQIWNH261GoqYnjNE8CP",
	"EZhQi9QKJYPT4FqKXzNgqXuGSZ4A66VaJFwv2XtY9hkMZ0M2CVUk5GzAZyDt5GAY9AOBr6fczoN+IGns",
	"IK3M1A80/JoJDVFwanUG/cCEc0g4kpAI+RLkzM6D0+N+YJcpvmysFnIWrFZ9pHghItDbSKaHumlWKUgu",
	"Jn33l1aZBb2J9nLO+xA/AmOEkhdRk3L/ExMRSCumAjTrEanX1xfPD5gGm2kJEZtqlTDOUg0LoTLDJsa9",
	"+J3KZDRhSrNwrgxINlWacSbhloVKLkAbjjN1rNAUhN19eSt81aRKGiBsfcejK/g1A2PxU6ikBUl/8jSN",
	"RUjkHKZa3cSQ/MsvBrnwsTLZXzRMg9Pg/x2W+D10v5rDS/fWc7BcxMbNXWfnKx5PlU4gYtrRwG5UtET2",
	"LHgsIpqcTbmIMw3DYNUPzpWcxiL8HLRegVGZDr2EhZ4Q1osyNzcgcA+IygtpQUsev9Ba6c9A6rWEDymE",
	"FiJmQC9AM0BKiLbXyn6PIPysHFSWTZEIouha8szOlRa/weeg6llm5yjMbhqWyxWCUEiCIQs1kLzz2AxJ",
	"Q/jRcfJnqE+9gn7xAcIMRxmBtULO6AEeRQK/4/GlViloK1Dwpjw20GBQJq1IYKBuUYdAPhqLYMqz2Bqn",
	"LSQjHZ5rfNQVaWVkVFn0+CsVQdxUYd9ncbwc/JrxGPVXlA/OEnycCckmuSI9pK8GiPcJTp3gVNuUZ6mX",
	"fq4T8q54Wt38AqHFra8y76Uw9sprpj35hq8yNWWGLyCqc8c02ZP/gn8LC4nZhqEqlQWFq2I5XGu+bKy9",
	"mGXbuu+45mdtq2XclGfQzZLZObBnlxdNHoQauIXomW3i42L0hn3z9dExo2cQfohJY3mS4jiIA26D0yDi",
	"Fgb4U9CAQT+IhEljvmw//n/MEi4HUy1ARvGyoD3mNxCzXsKX7AYYJKld0lHfGBzaxGzXDWzK6ArPWmN1",
	"FuLXpkmvf3NgUgjFVITsBuZ8IUhBlO+1kio32T8WwrkUIY+7jbd2BmgVQyeZDH9l7qcbIWdsLmbzQQwL",
	"iJk/+cWNiIVdto5tlYqvYNrChrdK4QhT0CBDMIwvuIj5TQzMKmbnwlQ1UiFYzQlqUtMPsjTaCsWYGztw",
	"D+6PxjXBlM48rCLUc3QNBxVetGGuXxGi6io65f0qkxVLa6Oo14U1AWP4DLah/NqAfuUePfdH6KofJO2n",
	"wJvUTe7VPjLlzMkcMxBDaA0pD+1OpOKQ6E1ew22+Ggn6Ev0UMyQNj6yctAF2bQPy5XQyamQ18OS8Ygbs",
	"rhaJEqYym2a5MSmZoQEhYhPn/TBYIOdOmYUPlqVcW8O4jJjKmTJBPExQF6Vpbs0/e/4T8wa4f/9gOJYT",
	"envCqlqL3c5BMiXjJUvA8ohbzkg6wIC0w7FsHkk4SHOTXu086BlTiSBgoqNHjJswNFk0xEt8jsexuoXI",
	"jWLnoAG/lYp45Eja/Sx0G3TJtW0T6E7tFGUhaDynEVkeBWc554j+nEA0EA1Y3Dt8NpMR6HiJqyPOI8ZA",
	"ZgmiKTOggxzm77ZhzzF6C/JeLDbizvlb9dWdc60F6kRmYhECLhLxkrt9Qxpywg7ZhAgdvnz5Kj/3J2wq",
	"II7w4I5hwaVFdRrGAtk+lj2CqAOwkLM+oVXwmIXzTL43fYZ7FAOScTBkI7L2DfGURxVAi8igQZsjpw2D",
	"zghvVdk3mstw3vpTxVjfETYV3UReybmKWuFCuC7w6u0ck+kpD9Hskc6nySHSkE52yF6+fJWfeNBuSOAI",
	"r0rt2nwgR0KoJKrtgKhoG0pErQMI9AR1llqo/n6jVAxcugcWynkeF+0j+P1uORxlqCEBaQsl7rTemeMZ",
	"aUfSahO0B88dTGCCYk8IdgjCj1OBEEHfAjmJT1e4VaG1Ok7batZkzTFvi6yREtnb8oUZLhydlUK1O3w4",
	"FgzZiw88tDEqf5JFFKI+w+P8nMdxH0XBne0GD7XNuhnfbTdk/HDbsP/WP/ecW15aWDjzLm+6J927qxZe",
	"npMRUncodjMy1p3zSgAGseDMfzlDndb0NFq8zk0mf2FuzDfY/l+Ysb/RE34I059dJElmycLmUwu68Mh2",
	"mP0BXYQtMz20w7Btuk1Ot9xkzTeR9K5TnvL49cPLkoTbMvAdKjkVs0wXu7p2JKfiJ1g2Gfvs8gIR4sJB",
	"tfDVkI2s0hChakxjjsfPB8t6sQp5fBjBgmUGDnbY1Btu4Fq3nDrfcQPs+uplbsYVS0GaQEapEs4+2zLB",
	"nbRFt5agA7DNgqbvq8iba5XN5gX8iPjhrtYvDXdOm9Zm+e4o8m2i/iozliXchnM2+a+f+eC3d/jP0eDb",
	"wbsnf5ncSxW4L1pUgdu4VCurQhUzfG7I3qCH4RMvA2QBt+ImdnaDydJUaQvRPehpl1h6qIRdP4d+m4Q+",
	"VxK2mOitbnTDmIuU3B4u6LZiqmDY14JxBlsTlryGyQc4YH1QDYazYZ+Ngx8u37KT4fE4ONgjXPW2QK6P",
	"Ea8lv3DgWWoH5cBbEGmyJOFa/MbdBEXEuoNdz8GImeQWjBNbRwUqv9pAzHLz3vh83AwkaKdzc7fAChuD",
	"wWN1ypIstiKNwY1l2JwvwA0OEjck6pN2mwptLBmRlK5AGcgMRM5M3GL+Ei87cXMhp+reqOGhVqZUY6bP",
	"hAzjLMJV15QzaRxk2HQt+J9vZdhxAj2wmn4ofDW9JL/SDXou17owFR/weFxnRRkIMywW76E9D7JDfKug",
	"pb8FAw+Q8Six4IHsIcHjuIRFc1vL43L3Y48Qu80A8wO3LXktE7dXeOXq+3P27cnTvzGfBGSRG4X1THZj",
	"wB60JcHwiQ6n3Fguw3aX31hus2rkGm2oGWhaOmqQDUHtj2U8OtOiFShtbKFdegAwtJuV7Rkwh4ydEVDa",
	"w7unv/wU7zYs+s65r/aldqS/WC83mPHw4OY9RAddxvalhoWA27ZYLL7H8pFS95w/bSbD4fDDf/x2PDkY",
	"stewABdJQQ2DD7dqrPtb2M1Y3J8oqbdzMu9Lt9yD+1rcbQN8ppxYhxWey0RXxqu/Se2PKoVPD2K1Vyup",
	"2nhnuqu3ro038kRE1tDk8s3oLTv0b5jDj8W7q0OKdg10Js1kuKOTUJ17Ayv20vR1ZuSU7qy3/ZSvfNy/",
	"DfpW2bbw8lv8msksuXE5m3xq56TmFuavGegl693AVGlgsUiEPVTTaX4krx+ha2wrlpNTsYFrxRL241hN",
	"J+6m5moAasp2bgO0FwbSz0P2LL7lS8OkkgOXvfvj978zDUbFi/JouuHhe5DRkP3gnBWI2EJwSlvUHZue",
	"mDK+9p03lQ2Lcu8oOuizCLRY5BnL0oPJDOg840bRb86IBSjpEZvyOEZanEuV7/OtsHOVWZzYhZTc0qqu",
	"T4fCuoMCqlY2Og7vk173zB+R6faQSsaN2AqSwkys4+Df52DngAzWmcTtCTOtQdp4SSE5rWYajPHJFmFy",
	"dlczmjy0YkHxyyiG7SnNQvc4ilr549KaWit9F+6EPkO3PT1GCbXWU75MsrWZDRp4RIe8r/U881ElZJHz",
	"xF2ehxKbKDI7a+RNxQZr2d5IIGGJkNy6PGjC0xTHRm5R3m97cvOFn5ZCSx2Pl/Ern4HsVN7r29avH36b",
	"dX7lxO2v4Xnzi1UxWhVY8GafZ+yqHygJb6bB6c87HUAVYlb9nd6oU7FzdnnHOdY5u+2Fcs9W71b9oJbS",
	"2893oaRImfXNC5/LU8EVCDTdEz3b02l+pmdZgqtgKTeo5ynrApT5ZL1/G715zZwsVI/qUjpE1GkQhzyO",
	"2cXzuilgXbbHZLHdJ/aDb00zSVkasq+3y7aINoVW1pKm+2ZuKCNcdSK5W1m5Zc29aWPVeRuPlBYzSrbT",
	"kMjGh2ZVWd2/H1hocF82tQ0be23HNZ3cj5CfJpOgOz/NJq5uGa39MlchI6ot4mEIKcrcHPS+qewf/2ky",
	"2F9WDpldQRrzEFzhInwQhtARC2MfLL98n8SyE4QHTixXhKAjqZzLgasEWqb4p4b9ZeIuueg3iaBqtvcA",
	"Ke2KN4bZgscZPFJY7D6J5x8/Ub55V6zeOaK1htucq624bJYN7wfK64pzWQ2rVCIo7BBRaYXMqKS4Vnjb",
	"485XJh8VBezMl39Ki8evr4Q82KdsNjOW5uNCMm5ZDNxn8fLCMfRtK845UeM8DtcvNTAigkoPWl4ajRtk",
	"SH40/OIarHDBtN4bFQkwe5TSVhjfXkq7c+3q+kj77d9IyBkilQpNy8o6XosasF61Q68lfN5RJre2Bnqq",
	"uYQVHWouI7omkW/fXpKIk36hEx4R5WInZZD/+U9sUilLp0rbq0xO2DRWt7iaPHGcUQjjrSttl6BxkYZN",
	"RnmBLUrVaPRicsZo5qJVEp9jT564AtvBCOkgf8A8ecJ6E1zWIXlGA+eoThCvY/nkiRuY0Kh5aE+fPGEv",
	"eDhno9GLgrVEgrFcRlxHbKqJENab0ICnk6KKt88mEbf8dMLQQMMZXixAL923ExYLSUXdnFXsNwd1Lpkb",
	"bcJqXi7rGYB89a5GuSSca8sWphBcJL1Fsm9gJqTxhU3ezTxzLrtrPeTGiJksW2AvoslY4qEDibCGCeu2",
	"Jw9VrXXKunrvXSO1Y5lTa6hCOFeseQlAz/AE6r2mZs5TOCueCFUCpgyfpdzOverxgb9ghFuRqKhEI3VI",
	"PLu8CPrBArRxwD0aHg+PyE9OQfJUBKfBX+mrPjX1ksx40qsNaTMgKULJKqqCKcFXNQpNsNbE+9XR0YbO",
	"yf06Jjt78lp6Jzc33q36wcnRcdd8xQIOaw2gq37w1K1m80v1HttVUVWyzMlC/6uNLtxKjkb4z64OufwB",
	"PftUmZYNaBbZ+g5sMPY7FS0fjPnd1byruipFH27VQMHxo6BgEwJqLGQ+ZOu3foddrHSf3xUtJ0ffbn+p",
	"6Bt/CHi5TcpVXhNimxC26q9L/eHHyqULK3cC5hX2dRQ+p+/XUFi9KaIjFlc+cli9SWL1roGfkxb7vrbB",
	"jrRoeI/dOtn+UtGj/hC75bjWHiVA+yHPfXbrhFad/APYx9yJo88ryV/SBv8A9j67m2Ytu9uMWj3ABj/8",
	"cdEdXNvpuPj0IHMEN3pJPulx8anx6dbM8niL7/ZzF7/c+fRAc5dcYG+vrAWf6YRas8r7znMqm+nINcCP",
	"M7EAuZYkRgvd+TLGt7syheb8aPTCO1DOsIeoatkznqbAtdlu0+dPuDmciV2XQfJAcqfukeyt9cbsO4lN",
	"w/ujlPIHnqTeqDf0J/5Fga88i3bKqnwZS3Lu2Mex+3UcnI5r+b5x0B+XiXL6+enTI/jm5OhoAF99ezM4",
	"OY5OBvxvx18PTk6+/vrp05OTo6Ojo3GwQo/Oz0g73zqV+wXn8C2HY58pGOdrHQenH92vZowacEwrp5d/",
	"hDhW42D1bnX3yVxwYlxrM9ybhj67VTqOhg1aIiWhlRT6AXlUudmlJfP19vvBN+S1e8A6N56G+eP3/zG5",
	"E07SjV44+eBF8qfmYo8lud05QkjUSmwetJZYNFVpSQsVApNEe0FFlzTO+/fzDmGgDmBKOFPwfw48LwH1",
	"cb/BW1+3VmWCL8xvgvyMhXOuDdh/zex08E0byZ9Qrd9bS7t4h1OYhWff0MWkdp0eLkPA3j5cD9Ujjl0l",
	"tq/NzgPzqPHbyrQ9pKTVS1/I7wPEtTr+sbTKtfMzKrugRITPL3bXtLNeezn7WlytTQ+jN+3i2o8ZdmhW",
	"xG+IN6yXvf8ZYg07leJXAOVZ6sBUq8jujAFdVoZ5tI1oLUjfsBedVeeff0s6SKtsQsnRbcGfy7Kr4/EC",
	"P+vZwU8c9GlW+Te3/bK98v6fMPLTjq4OcNWEnEI+xV2VO8R8KuDb2wkt78TcLeDTscFfcuSno1ukGR6o",
	"q4OuuM+j7cbRn0CSv7zIzx13d0Pc5yE3+LGCPnc6Kj4twPJgT7oJaP/gUZ87whOPi2qzx0YXI89dFveC",
	"9UTUd+X6/bI1yHhbP46LGv+xvIFYyRm5D644tFLCAxGFhPrMUM8/UhxzY1ml54j1EmUs0xCiA0HBnoMu",
	"F2JUNnusCdV6o90HkWRJW+uJVb4yk/WO//j9v4+Pjsq7oKkTpbwqmVpRNl+T7OYJTo+PjqhqyH9q61pZ",
	"p/F1K23mvUhZD5mc8pmQ3F/K9Ty/vdUqdtRFr2uaCfptvneVvKMW8h7zIGnrWWo7S9yCIaISmQpjyivH",
	"gi8pGkAuRLG3+dVYTeGoiG+B77r0VksVNkhyGvOl8xXnwlilqd2wft0g44YCUFMUHkPXGLR0mbjukZzk",
	"sSyCv5UuCmNxMpWC9LGnvGZiqvQt15GrRVvAlnjScCwvpr7Uw1+LbpiISOuUk4GMjK9CYZNIScgDwK7g",
	"StPSXQEpLnxJ9Se+bEbpCPTpWB4P22PIPdKpOjF1KqKDsfyqfMW1EhTvTByL6Bb2CZI7ORjLvw7Zf4JW",
	"dEme0rB2U6SnMm+s8pSO5YnbBRrvtMJHWi5xcG2cOienQgozBzOWT4c13rSo0CvgkYfY3mZJeaH9Drqi",
	"NZp9l7Do/98rKLp/1LNETl1Ozqr4FhUhcfv0J499nnyGK9Dz5sX6vez3VqII2XUd1nO7lotQ7drVeMmQ",
	"RCc4OpMHm8KvW0rBunNjI1JIzoWvVTj6hJRLhuVkV9NgZeYsX381JTZqlJZxwyammsSanNVyZcIwy9+D",
	"rJebsV7xn0cIpceyVfFR8tCVxg78/ySBNl8EKUhS30rm9XepikW4bDXLzr3CqiTZ7qdY/uESdI+ULhtl",
	"Gtgfv//9/lmq/0sT3cUP/OT/8YVvJ6Prm8W0Wh7ri8wp08NtzY6h8lXDfHO9zqQUcoZGF24U3fxqneuB",
	"L/oqet9jXtquvRnYgdIDF6A9oA5aRX0Zc2HK63HH8mECpHmVf/G/VJCd4/7bivVy3E71Tk34dJNxi394",
	"BTEnE9d7rFSn7Zl545tEgn6Q6Tg4DQ5JMflZGicBpfyULnsTnKmAOh9dWpyk9X7Z0m2r0N30El0eQkZM",
	"SJNCaFESSq+iHKTwHJpDvOISj6aXL191JTNY7/zq+vlBOVoZRugcrq1Wasuoa6UoXYvdkAOrZD+r6TA/",
	"vs+Grd6t/jcAAP//WjuDGAtrAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
