//go:build go1.22

// Package agentapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260404004943-9ea3cc79a4c7 DO NOT EDIT.
package agentapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AgentProfileRegularExecutionSettingsMode.
const (
	Regular AgentProfileRegularExecutionSettingsMode = "regular"
)

// Valid indicates whether the value is a known member of the AgentProfileRegularExecutionSettingsMode enum.
func (e AgentProfileRegularExecutionSettingsMode) Valid() bool {
	switch e {
	case Regular:
		return true
	default:
		return false
	}
}

// Defines values for AgentStreamContentRole.
const (
	Model AgentStreamContentRole = "model"
	User  AgentStreamContentRole = "user"
)

// Valid indicates whether the value is a known member of the AgentStreamContentRole enum.
func (e AgentStreamContentRole) Valid() bool {
	switch e {
	case Model:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatusEventStatus.
const (
	Active SessionStatusEventStatus = "active"
	Idle   SessionStatusEventStatus = "idle"
)

// Valid indicates whether the value is a known member of the SessionStatusEventStatus enum.
func (e SessionStatusEventStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Idle:
		return true
	default:
		return false
	}
}

// ACPStdioAgentCommand Command defaults used to launch an ACP-compatible stdio agent.
type ACPStdioAgentCommand struct {
	// Args Command arguments passed to the ACP-compatible stdio agent executable.
	Args *[]string `json:"args,omitempty"`

	// Command Command executable to launch the ACP-compatible stdio agent.
	Command string `json:"command"`
}

// AgentProfileACPStdioExecutionSettings Runtime-owned execution defaults for ACP-compatible stdio profile execution.
type AgentProfileACPStdioExecutionSettings struct {
	// AgentCommand Command defaults used to launch an ACP-compatible stdio agent.
	AgentCommand ACPStdioAgentCommand `json:"agentCommand"`

	// Cwd Optional working directory used to launch the ACP stdio agent.
	Cwd *string `json:"cwd,omitempty"`

	// Mode Execution mode for ACP-compatible stdio profiles.
	Mode string `json:"mode"`
}

// AgentProfileExecutionSettings defines model for AgentProfileExecutionSettings.
type AgentProfileExecutionSettings struct {
	union json.RawMessage
}

// AgentProfileListResponse List of saved agent profiles.
type AgentProfileListResponse struct {
	Profiles []AgentProfileResponse `json:"profiles"`
}

// AgentProfileRegularExecutionSettings Runtime-owned execution defaults for built-in profile execution.
type AgentProfileRegularExecutionSettings struct {
	// DefaultModel Fully-qualified default model in `provider/model-name` form.
	DefaultModel string `json:"defaultModel"`

	// Mode Execution mode. Omit for regular built-in execution.
	Mode *AgentProfileRegularExecutionSettingsMode `json:"mode,omitempty"`
}

// AgentProfileRegularExecutionSettingsMode Execution mode. Omit for regular built-in execution.
type AgentProfileRegularExecutionSettingsMode string

// AgentProfileResponse A saved agent profile as returned by the API.
type AgentProfileResponse struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"createdAt"`

	// DisplayName Human-friendly profile label (may be empty).
	DisplayName       string                        `json:"displayName"`
	ExecutionSettings AgentProfileExecutionSettings `json:"executionSettings"`

	// Instructions Profile-specific behavior instructions.
	Instructions string `json:"instructions"`

	// Name Unique technical profile name (primary key).
	Name string `json:"name"`

	// Role Profile role describing high-level responsibility.
	Role string `json:"role"`

	// ToolRefs Tool references available to this profile.
	ToolRefs []string `json:"toolRefs"`

	// UpdatedAt ISO 8601 last-update timestamp.
	UpdatedAt time.Time `json:"updatedAt"`
}

// AgentRunRequest defines model for AgentRunRequest.
type AgentRunRequest struct {
	// Message User message for `POST /agent-runs` / continue run: text parts (always user role; not sent by clients).
	Message UserMessageContent `json:"message"`

	// Model Optional model name; empty selects the runtime default (`NewAgentRunnerParams.ModelName`).
	Model *string `json:"model,omitempty"`
}

// AgentStreamContent Model output body on streamed `agent` events: text parts and optional `role` (mapped from ADK session events).
// `parts` may be empty when only metadata is present.
type AgentStreamContent struct {
	// Parts May be empty when only metadata is present; omitting `content` entirely is allowed when there is no body.
	Parts []AgentStreamPart `json:"parts"`

	// Role Producer of the message; may be omitted when not set on the underlying event.
	Role *AgentStreamContentRole `json:"role,omitempty"`
}

// AgentStreamContentRole Producer of the message; may be omitted when not set on the underlying event.
type AgentStreamContentRole string

// AgentStreamEvent Carries a slice of ADK `session.Event` / `model.LLMResponse` fields relevant to clients
// (text streaming, partial chunks, completion). Servers may add optional ids or metadata.
type AgentStreamEvent struct {
	Author *string `json:"author,omitempty"`
	Branch *string `json:"branch,omitempty"`

	// Content Model output body on streamed `agent` events: text parts and optional `role` (mapped from ADK session events).
	// `parts` may be empty when only metadata is present.
	Content *AgentStreamContent `json:"content,omitempty"`

	// ErrorCode Present when the agent surfaced an error on the ADK session event / LLM response.
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	Event        string  `json:"event"`
	Id           *string `json:"id,omitempty"`
	Interrupted  *bool   `json:"interrupted,omitempty"`
	InvocationId *string `json:"invocationId,omitempty"`

	// Partial Incremental model output; when false and `turnComplete` is true, chunk is final for the turn.
	Partial              *bool                  `json:"partial,omitempty"`
	TurnComplete         *bool                  `json:"turnComplete,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// AgentStreamPart A segment in streamed agent output. Exactly one of text, toolCall, or toolResult is present.
type AgentStreamPart struct {
	Text *string `json:"text,omitempty"`

	// ToolCall Tool invocation requested by the model.
	ToolCall *ToolCallData `json:"toolCall,omitempty"`

	// ToolResult Result returned by a tool invocation.
	ToolResult *ToolResultData `json:"toolResult,omitempty"`
}

// CreateAgentProfileRequest Request body for creating a saved agent profile.
type CreateAgentProfileRequest struct {
	// DisplayName Optional human-friendly profile label.
	DisplayName       *string                       `json:"displayName,omitempty"`
	ExecutionSettings AgentProfileExecutionSettings `json:"executionSettings"`

	// Instructions Profile-specific behavior instructions.
	Instructions string `json:"instructions"`

	// Name Unique technical profile name (primary key). Immutable after creation.
	Name string `json:"name"`

	// Role Profile role describing high-level responsibility.
	Role string `json:"role"`

	// ToolRefs Tool references available to this profile.
	ToolRefs *[]string `json:"toolRefs,omitempty"`
}

// CreateOpenCodeBindingRequest Request body for creating an OpenCode binding.
type CreateOpenCodeBindingRequest struct {
	// AgentCommand OpenCode command defaults used to launch ACP.
	AgentCommand OpenCodeAgentCommand `json:"agentCommand"`

	// Cwd Optional working directory used for OpenCode launch.
	Cwd *string `json:"cwd,omitempty"`

	// LaunchOptions OpenCode launch defaults.
	LaunchOptions OpenCodeLaunchOptions `json:"launchOptions"`

	// Name Unique technical binding name (primary key).
	Name string `json:"name"`

	// ProfileName Name of the saved general profile associated with this binding.
	ProfileName string `json:"profileName"`
}

// CreateOpenCodeLaunchRequest Launch input selecting saved profile and optional binding.
type CreateOpenCodeLaunchRequest struct {
	// BindingName Optional saved binding selector. When omitted, the first binding for the profile is used.
	BindingName *string `json:"bindingName,omitempty"`

	// ProfileName Saved profile selector.
	ProfileName string `json:"profileName"`

	// Prompt User prompt forwarded to OpenCode launch flow.
	Prompt string `json:"prompt"`
}

// CreateProviderRequest Request body for creating a new provider configuration.
type CreateProviderRequest struct {
	// ApiKey API key for authentication. Stored in plaintext (local/dev use).
	ApiKey string `json:"apiKey"`

	// BaseUrl Base URL of the provider API endpoint.
	BaseUrl string `json:"baseUrl"`

	// DisplayName Optional human-friendly label.
	DisplayName *string `json:"displayName,omitempty"`

	// Models Models available through this provider.
	Models *[]ModelConfig `json:"models,omitempty"`

	// Name Unique technical name (primary key). Must match `^[a-z][a-z0-9-]*$`. Immutable after creation.
	Name string `json:"name"`

	// Type Provider protocol type. Only `openai-compatible` is supported. Immutable after creation.
	Type string `json:"type"`
}

// DoneEvent defines model for DoneEvent.
type DoneEvent struct {
	Event string `json:"event"`
}

// ModelConfig A model available through a provider.
type ModelConfig struct {
	// DisplayName Optional human-friendly label (e.g., "GPT 4.1").
	DisplayName *string `json:"displayName,omitempty"`

	// Name Technical model identifier (e.g., "gpt-4.1").
	Name string `json:"name"`

	// Summarization Designates this model for summarization tasks (e.g. generating session titles). If multiple models have this enabled, the first one found is used.
	Summarization *bool `json:"summarization,omitempty"`
}

// ModelInfo A model available across providers, including the provider name for fully-qualified identification.
type ModelInfo struct {
	// DisplayName Optional human-friendly label.
	DisplayName *string `json:"displayName,omitempty"`

	// Name Technical model identifier (e.g., "gpt-4.1").
	Name string `json:"name"`

	// Provider Provider name (prefix in fully-qualified model names like `provider/model-name`).
	Provider string `json:"provider"`
}

// ModelListResponse List of available models across all providers.
type ModelListResponse struct {
	Models []ModelInfo `json:"models"`
}

// OpenCodeAgentCommand OpenCode command defaults used to launch ACP.
type OpenCodeAgentCommand struct {
	// Args Command arguments passed as-is to the OpenCode executable.
	Args []string `json:"args"`

	// Command Command executable to run OpenCode.
	Command string `json:"command"`
}

// OpenCodeBindingListResponse List of saved OpenCode bindings.
type OpenCodeBindingListResponse struct {
	Bindings []OpenCodeBindingResponse `json:"bindings"`
}

// OpenCodeBindingResponse A saved OpenCode binding as returned by the API.
type OpenCodeBindingResponse struct {
	// AgentCommand OpenCode command defaults used to launch ACP.
	AgentCommand OpenCodeAgentCommand `json:"agentCommand"`
	CreatedAt    time.Time            `json:"createdAt"`
	Cwd          string               `json:"cwd"`

	// LaunchOptions OpenCode launch defaults.
	LaunchOptions OpenCodeLaunchOptions `json:"launchOptions"`
	Name          string                `json:"name"`
	ProfileName   string                `json:"profileName"`
	UpdatedAt     time.Time             `json:"updatedAt"`
}

// OpenCodeLaunchOptions OpenCode launch defaults.
type OpenCodeLaunchOptions struct {
	// Transport ACP transport mode. Only `stdio` is supported.
	Transport string `json:"transport"`
}

// OpenCodeLaunchResponse Result of a launched OpenCode coding run.
type OpenCodeLaunchResponse struct {
	BindingName  string                 `json:"bindingName"`
	ProfileName  string                 `json:"profileName"`
	PromptResult map[string]interface{} `json:"promptResult"`
	SessionId    string                 `json:"sessionId"`
	Updates      []OpenCodeLaunchUpdate `json:"updates"`
}

// OpenCodeLaunchUpdate Parsed ACP session/update notification from launch execution.
type OpenCodeLaunchUpdate struct {
	Payload   map[string]interface{} `json:"payload"`
	SessionId string                 `json:"sessionId"`
	Type      string                 `json:"type"`
}

// ProblemDetails RFC 9457 problem details (subset).
type ProblemDetails struct {
	Detail               *string                `json:"detail,omitempty"`
	Instance             *string                `json:"instance,omitempty"`
	Status               *int                   `json:"status,omitempty"`
	Title                *string                `json:"title,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ProviderListResponse List of provider configurations.
type ProviderListResponse struct {
	Providers []ProviderResponse `json:"providers"`
}

// ProviderResponse A provider configuration as returned by the API (API key is masked).
type ProviderResponse struct {
	// ApiKeyPreview Masked API key preview (e.g. `...xYz1`). Never the full key.
	ApiKeyPreview string `json:"apiKeyPreview"`

	// BaseUrl Base URL of the provider API endpoint.
	BaseUrl string `json:"baseUrl"`

	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"createdAt"`

	// DisplayName Human-friendly label (may be empty).
	DisplayName *string `json:"displayName,omitempty"`

	// Models Models available through this provider.
	Models []ModelConfig `json:"models"`

	// Name Unique technical name (primary key).
	Name string `json:"name"`

	// Type Provider protocol type.
	Type string `json:"type"`

	// UpdatedAt ISO 8601 last-update timestamp.
	UpdatedAt time.Time `json:"updatedAt"`
}

// SessionBoundEvent defines model for SessionBoundEvent.
type SessionBoundEvent struct {
	Event string `json:"event"`

	// SessionId Use this id for `POST /sessions/{sessionId}/agent-runs`.
	SessionId string `json:"sessionId"`
}

// SessionListResponse defines model for SessionListResponse.
type SessionListResponse struct {
	Sessions []SessionMetadata `json:"sessions"`

	// Total Total number of sessions matching the query (before limit/offset).
	Total int `json:"total"`
}

// SessionMetadata defines model for SessionMetadata.
type SessionMetadata struct {
	CreatedAt time.Time `json:"createdAt"`
	SessionId string    `json:"sessionId"`

	// Title Session title. Always non-empty — resolved by the backend. Generated via LLM summarization (if a summarization model is designated), derived from the first user message, or a date-based fallback for sessions without a stored title.
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// SessionStatusEvent defines model for SessionStatusEvent.
type SessionStatusEvent struct {
	Event string `json:"event"`

	// Status Whether a run is currently in progress for this session.
	Status SessionStatusEventStatus `json:"status"`
}

// SessionStatusEventStatus Whether a run is currently in progress for this session.
type SessionStatusEventStatus string

// StreamErrorEvent defines model for StreamErrorEvent.
type StreamErrorEvent struct {
	Code  *string `json:"code,omitempty"`
	Event string  `json:"event"`

	// Message Human-readable failure; after this, the stream may end.
	Message string `json:"message"`
}

// StreamEvent defines model for StreamEvent.
type StreamEvent struct {
	union json.RawMessage
}

// ToolCallData Tool invocation requested by the model.
type ToolCallData struct {
	// Args Arguments passed to the tool (JSON object).
	Args *map[string]interface{} `json:"args,omitempty"`

	// Id Unique call ID matching the tool result.
	Id string `json:"id"`

	// Name Tool function name.
	Name string `json:"name"`
}

// ToolResultData Result returned by a tool invocation.
type ToolResultData struct {
	// Id Call ID matching the original tool call.
	Id string `json:"id"`

	// Name Tool function name.
	Name string `json:"name"`

	// Response Tool output (JSON object).
	Response *map[string]interface{} `json:"response,omitempty"`
}

// UpdateAgentProfileRequest Request body for updating a saved agent profile. `name` is immutable and not accepted here.
type UpdateAgentProfileRequest struct {
	// DisplayName Human-friendly profile label.
	DisplayName       *string                       `json:"displayName,omitempty"`
	ExecutionSettings AgentProfileExecutionSettings `json:"executionSettings"`

	// Instructions Profile-specific behavior instructions.
	Instructions string `json:"instructions"`

	// Role Profile role describing high-level responsibility.
	Role string `json:"role"`

	// ToolRefs Tool references available to this profile. Replaces the existing list.
	ToolRefs *[]string `json:"toolRefs,omitempty"`
}

// UpdateOpenCodeBindingRequest Request body for updating mutable OpenCode binding fields.
type UpdateOpenCodeBindingRequest struct {
	// AgentCommand OpenCode command defaults used to launch ACP.
	AgentCommand OpenCodeAgentCommand `json:"agentCommand"`

	// Cwd Working directory used for OpenCode launch.
	Cwd *string `json:"cwd,omitempty"`

	// LaunchOptions OpenCode launch defaults.
	LaunchOptions OpenCodeLaunchOptions `json:"launchOptions"`
}

// UpdateProviderRequest Request body for updating a provider configuration. `name` and `type` are immutable and not accepted here.
type UpdateProviderRequest struct {
	// ApiKey API key for authentication. Omit to keep the current value.
	ApiKey *string `json:"apiKey,omitempty"`

	// BaseUrl Base URL of the provider API endpoint.
	BaseUrl string `json:"baseUrl"`

	// DisplayName Human-friendly label.
	DisplayName *string `json:"displayName,omitempty"`

	// Models Models available through this provider. Replaces the existing list.
	Models *[]ModelConfig `json:"models,omitempty"`
}

// UserMessageContent User message for `POST /agent-runs` / continue run: text parts (always user role; not sent by clients).
type UserMessageContent struct {
	// Parts Must contain at least one segment with non-empty text after server-side validation; empty lists are rejected for POST bodies.
	Parts []UserMessagePart `json:"parts"`
}

// UserMessagePart Single text segment in a user message (request body).
type UserMessagePart struct {
	Text string `json:"text"`
}

// BindingName defines model for BindingName.
type BindingName = string

// ProfileName defines model for ProfileName.
type ProfileName = string

// ProviderName defines model for ProviderName.
type ProviderName = string

// SessionId defines model for SessionId.
type SessionId = string

// BadRequest RFC 9457 problem details (subset).
type BadRequest = ProblemDetails

// Conflict RFC 9457 problem details (subset).
type Conflict = ProblemDetails

// InternalError RFC 9457 problem details (subset).
type InternalError = ProblemDetails

// NotFound RFC 9457 problem details (subset).
type NotFound = ProblemDetails

// Unauthorized RFC 9457 problem details (subset).
type Unauthorized = ProblemDetails

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	// Limit Maximum number of sessions to return (1–100).
	Limit int `form:"limit" json:"limit"`

	// Offset Number of sessions to skip (for pagination). Defaults to 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateAgentProfileJSONRequestBody defines body for CreateAgentProfile for application/json ContentType.
type CreateAgentProfileJSONRequestBody = CreateAgentProfileRequest

// UpdateAgentProfileJSONRequestBody defines body for UpdateAgentProfile for application/json ContentType.
type UpdateAgentProfileJSONRequestBody = UpdateAgentProfileRequest

// StartAgentRunJSONRequestBody defines body for StartAgentRun for application/json ContentType.
type StartAgentRunJSONRequestBody = AgentRunRequest

// CreateOpenCodeBindingJSONRequestBody defines body for CreateOpenCodeBinding for application/json ContentType.
type CreateOpenCodeBindingJSONRequestBody = CreateOpenCodeBindingRequest

// UpdateOpenCodeBindingJSONRequestBody defines body for UpdateOpenCodeBinding for application/json ContentType.
type UpdateOpenCodeBindingJSONRequestBody = UpdateOpenCodeBindingRequest

// CreateOpenCodeLaunchJSONRequestBody defines body for CreateOpenCodeLaunch for application/json ContentType.
type CreateOpenCodeLaunchJSONRequestBody = CreateOpenCodeLaunchRequest

// CreateProviderJSONRequestBody defines body for CreateProvider for application/json ContentType.
type CreateProviderJSONRequestBody = CreateProviderRequest

// UpdateProviderJSONRequestBody defines body for UpdateProvider for application/json ContentType.
type UpdateProviderJSONRequestBody = UpdateProviderRequest

// ContinueAgentRunJSONRequestBody defines body for ContinueAgentRun for application/json ContentType.
type ContinueAgentRunJSONRequestBody = AgentRunRequest

// Getter for additional properties for AgentStreamEvent. Returns the specified
// element and whether it was found
func (a AgentStreamEvent) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AgentStreamEvent
func (a *AgentStreamEvent) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AgentStreamEvent to handle AdditionalProperties
func (a *AgentStreamEvent) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["author"]; found {
		err = json.Unmarshal(raw, &a.Author)
		if err != nil {
			return fmt.Errorf("error reading 'author': %w", err)
		}
		delete(object, "author")
	}

	if raw, found := object["branch"]; found {
		err = json.Unmarshal(raw, &a.Branch)
		if err != nil {
			return fmt.Errorf("error reading 'branch': %w", err)
		}
		delete(object, "branch")
	}

	if raw, found := object["content"]; found {
		err = json.Unmarshal(raw, &a.Content)
		if err != nil {
			return fmt.Errorf("error reading 'content': %w", err)
		}
		delete(object, "content")
	}

	if raw, found := object["errorCode"]; found {
		err = json.Unmarshal(raw, &a.ErrorCode)
		if err != nil {
			return fmt.Errorf("error reading 'errorCode': %w", err)
		}
		delete(object, "errorCode")
	}

	if raw, found := object["errorMessage"]; found {
		err = json.Unmarshal(raw, &a.ErrorMessage)
		if err != nil {
			return fmt.Errorf("error reading 'errorMessage': %w", err)
		}
		delete(object, "errorMessage")
	}

	if raw, found := object["event"]; found {
		err = json.Unmarshal(raw, &a.Event)
		if err != nil {
			return fmt.Errorf("error reading 'event': %w", err)
		}
		delete(object, "event")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["interrupted"]; found {
		err = json.Unmarshal(raw, &a.Interrupted)
		if err != nil {
			return fmt.Errorf("error reading 'interrupted': %w", err)
		}
		delete(object, "interrupted")
	}

	if raw, found := object["invocationId"]; found {
		err = json.Unmarshal(raw, &a.InvocationId)
		if err != nil {
			return fmt.Errorf("error reading 'invocationId': %w", err)
		}
		delete(object, "invocationId")
	}

	if raw, found := object["partial"]; found {
		err = json.Unmarshal(raw, &a.Partial)
		if err != nil {
			return fmt.Errorf("error reading 'partial': %w", err)
		}
		delete(object, "partial")
	}

	if raw, found := object["turnComplete"]; found {
		err = json.Unmarshal(raw, &a.TurnComplete)
		if err != nil {
			return fmt.Errorf("error reading 'turnComplete': %w", err)
		}
		delete(object, "turnComplete")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AgentStreamEvent to handle AdditionalProperties
func (a AgentStreamEvent) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Author != nil {
		object["author"], err = json.Marshal(a.Author)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'author': %w", err)
		}
	}

	if a.Branch != nil {
		object["branch"], err = json.Marshal(a.Branch)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'branch': %w", err)
		}
	}

	if a.Content != nil {
		object["content"], err = json.Marshal(a.Content)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'content': %w", err)
		}
	}

	if a.ErrorCode != nil {
		object["errorCode"], err = json.Marshal(a.ErrorCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'errorCode': %w", err)
		}
	}

	if a.ErrorMessage != nil {
		object["errorMessage"], err = json.Marshal(a.ErrorMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'errorMessage': %w", err)
		}
	}

	object["event"], err = json.Marshal(a.Event)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'event': %w", err)
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Interrupted != nil {
		object["interrupted"], err = json.Marshal(a.Interrupted)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'interrupted': %w", err)
		}
	}

	if a.InvocationId != nil {
		object["invocationId"], err = json.Marshal(a.InvocationId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'invocationId': %w", err)
		}
	}

	if a.Partial != nil {
		object["partial"], err = json.Marshal(a.Partial)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'partial': %w", err)
		}
	}

	if a.TurnComplete != nil {
		object["turnComplete"], err = json.Marshal(a.TurnComplete)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'turnComplete': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ProblemDetails. Returns the specified
// element and whether it was found
func (a ProblemDetails) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemDetails
func (a *ProblemDetails) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a *ProblemDetails) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a ProblemDetails) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsAgentProfileRegularExecutionSettings returns the union data inside the AgentProfileExecutionSettings as a AgentProfileRegularExecutionSettings
func (t AgentProfileExecutionSettings) AsAgentProfileRegularExecutionSettings() (AgentProfileRegularExecutionSettings, error) {
	var body AgentProfileRegularExecutionSettings
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentProfileRegularExecutionSettings overwrites any union data inside the AgentProfileExecutionSettings as the provided AgentProfileRegularExecutionSettings
func (t *AgentProfileExecutionSettings) FromAgentProfileRegularExecutionSettings(v AgentProfileRegularExecutionSettings) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentProfileRegularExecutionSettings performs a merge with any union data inside the AgentProfileExecutionSettings, using the provided AgentProfileRegularExecutionSettings
func (t *AgentProfileExecutionSettings) MergeAgentProfileRegularExecutionSettings(v AgentProfileRegularExecutionSettings) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAgentProfileACPStdioExecutionSettings returns the union data inside the AgentProfileExecutionSettings as a AgentProfileACPStdioExecutionSettings
func (t AgentProfileExecutionSettings) AsAgentProfileACPStdioExecutionSettings() (AgentProfileACPStdioExecutionSettings, error) {
	var body AgentProfileACPStdioExecutionSettings
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentProfileACPStdioExecutionSettings overwrites any union data inside the AgentProfileExecutionSettings as the provided AgentProfileACPStdioExecutionSettings
func (t *AgentProfileExecutionSettings) FromAgentProfileACPStdioExecutionSettings(v AgentProfileACPStdioExecutionSettings) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentProfileACPStdioExecutionSettings performs a merge with any union data inside the AgentProfileExecutionSettings, using the provided AgentProfileACPStdioExecutionSettings
func (t *AgentProfileExecutionSettings) MergeAgentProfileACPStdioExecutionSettings(v AgentProfileACPStdioExecutionSettings) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AgentProfileExecutionSettings) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AgentProfileExecutionSettings) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSessionBoundEvent returns the union data inside the StreamEvent as a SessionBoundEvent
func (t StreamEvent) AsSessionBoundEvent() (SessionBoundEvent, error) {
	var body SessionBoundEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSessionBoundEvent overwrites any union data inside the StreamEvent as the provided SessionBoundEvent
func (t *StreamEvent) FromSessionBoundEvent(v SessionBoundEvent) error {
	v.Event = "sessionBound"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSessionBoundEvent performs a merge with any union data inside the StreamEvent, using the provided SessionBoundEvent
func (t *StreamEvent) MergeSessionBoundEvent(v SessionBoundEvent) error {
	v.Event = "sessionBound"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSessionStatusEvent returns the union data inside the StreamEvent as a SessionStatusEvent
func (t StreamEvent) AsSessionStatusEvent() (SessionStatusEvent, error) {
	var body SessionStatusEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSessionStatusEvent overwrites any union data inside the StreamEvent as the provided SessionStatusEvent
func (t *StreamEvent) FromSessionStatusEvent(v SessionStatusEvent) error {
	v.Event = "sessionStatus"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSessionStatusEvent performs a merge with any union data inside the StreamEvent, using the provided SessionStatusEvent
func (t *StreamEvent) MergeSessionStatusEvent(v SessionStatusEvent) error {
	v.Event = "sessionStatus"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAgentStreamEvent returns the union data inside the StreamEvent as a AgentStreamEvent
func (t StreamEvent) AsAgentStreamEvent() (AgentStreamEvent, error) {
	var body AgentStreamEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentStreamEvent overwrites any union data inside the StreamEvent as the provided AgentStreamEvent
func (t *StreamEvent) FromAgentStreamEvent(v AgentStreamEvent) error {
	v.Event = "agent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentStreamEvent performs a merge with any union data inside the StreamEvent, using the provided AgentStreamEvent
func (t *StreamEvent) MergeAgentStreamEvent(v AgentStreamEvent) error {
	v.Event = "agent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStreamErrorEvent returns the union data inside the StreamEvent as a StreamErrorEvent
func (t StreamEvent) AsStreamErrorEvent() (StreamErrorEvent, error) {
	var body StreamErrorEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreamErrorEvent overwrites any union data inside the StreamEvent as the provided StreamErrorEvent
func (t *StreamEvent) FromStreamErrorEvent(v StreamErrorEvent) error {
	v.Event = "error"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStreamErrorEvent performs a merge with any union data inside the StreamEvent, using the provided StreamErrorEvent
func (t *StreamEvent) MergeStreamErrorEvent(v StreamErrorEvent) error {
	v.Event = "error"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDoneEvent returns the union data inside the StreamEvent as a DoneEvent
func (t StreamEvent) AsDoneEvent() (DoneEvent, error) {
	var body DoneEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDoneEvent overwrites any union data inside the StreamEvent as the provided DoneEvent
func (t *StreamEvent) FromDoneEvent(v DoneEvent) error {
	v.Event = "done"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDoneEvent performs a merge with any union data inside the StreamEvent, using the provided DoneEvent
func (t *StreamEvent) MergeDoneEvent(v DoneEvent) error {
	v.Event = "done"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StreamEvent) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"event"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t StreamEvent) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "agent":
		return t.AsAgentStreamEvent()
	case "done":
		return t.AsDoneEvent()
	case "error":
		return t.AsStreamErrorEvent()
	case "sessionBound":
		return t.AsSessionBoundEvent()
	case "sessionStatus":
		return t.AsSessionStatusEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t StreamEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StreamEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all saved agent profiles
	// (GET /agent-profiles)
	ListAgentProfiles(w http.ResponseWriter, r *http.Request)
	// Create a new saved agent profile
	// (POST /agent-profiles)
	CreateAgentProfile(w http.ResponseWriter, r *http.Request)
	// Delete a saved agent profile by name
	// (DELETE /agent-profiles/{profileName})
	DeleteAgentProfile(w http.ResponseWriter, r *http.Request, profileName ProfileName)
	// Get a saved agent profile by name
	// (GET /agent-profiles/{profileName})
	GetAgentProfile(w http.ResponseWriter, r *http.Request, profileName ProfileName)
	// Update mutable fields for a saved agent profile
	// (PUT /agent-profiles/{profileName})
	UpdateAgentProfile(w http.ResponseWriter, r *http.Request, profileName ProfileName)
	// Start a new agent run
	// (POST /agent-runs)
	StartAgentRun(w http.ResponseWriter, r *http.Request)
	// List all available models across all providers
	// (GET /models)
	ListModels(w http.ResponseWriter, r *http.Request)
	// List all saved OpenCode bindings
	// (GET /opencode-bindings)
	ListOpenCodeBindings(w http.ResponseWriter, r *http.Request)
	// Create a new saved OpenCode binding
	// (POST /opencode-bindings)
	CreateOpenCodeBinding(w http.ResponseWriter, r *http.Request)
	// Delete a saved OpenCode binding by name
	// (DELETE /opencode-bindings/{bindingName})
	DeleteOpenCodeBinding(w http.ResponseWriter, r *http.Request, bindingName BindingName)
	// Get a saved OpenCode binding by name
	// (GET /opencode-bindings/{bindingName})
	GetOpenCodeBinding(w http.ResponseWriter, r *http.Request, bindingName BindingName)
	// Update mutable fields for a saved OpenCode binding
	// (PUT /opencode-bindings/{bindingName})
	UpdateOpenCodeBinding(w http.ResponseWriter, r *http.Request, bindingName BindingName)
	// Launch OpenCode coding run from saved profile and binding selectors
	// (POST /opencode-launches)
	CreateOpenCodeLaunch(w http.ResponseWriter, r *http.Request)
	// List all provider configurations
	// (GET /providers)
	ListProviders(w http.ResponseWriter, r *http.Request)
	// Create a new provider configuration
	// (POST /providers)
	CreateProvider(w http.ResponseWriter, r *http.Request)
	// Delete a provider configuration by name
	// (DELETE /providers/{providerName})
	DeleteProvider(w http.ResponseWriter, r *http.Request, providerName ProviderName)
	// Get a provider configuration by name
	// (GET /providers/{providerName})
	GetProvider(w http.ResponseWriter, r *http.Request, providerName ProviderName)
	// Update a provider configuration by name
	// (PUT /providers/{providerName})
	UpdateProvider(w http.ResponseWriter, r *http.Request, providerName ProviderName)
	// List sessions for the authenticated user
	// (GET /sessions)
	ListSessions(w http.ResponseWriter, r *http.Request, params ListSessionsParams)
	// Read session events (replay history and optionally tail live run)
	// (GET /sessions/{sessionId})
	ReadSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Continue an agent run for an existing session
	// (POST /sessions/{sessionId}/agent-runs)
	ContinueAgentRun(w http.ResponseWriter, r *http.Request, sessionId SessionId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAgentProfiles operation middleware
func (siw *ServerInterfaceWrapper) ListAgentProfiles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgentProfiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAgentProfile operation middleware
func (siw *ServerInterfaceWrapper) CreateAgentProfile(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAgentProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAgentProfile operation middleware
func (siw *ServerInterfaceWrapper) DeleteAgentProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "profileName" -------------
	var profileName ProfileName

	err = runtime.BindStyledParameterWithOptions("simple", "profileName", r.PathValue("profileName"), &profileName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAgentProfile(w, r, profileName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgentProfile operation middleware
func (siw *ServerInterfaceWrapper) GetAgentProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "profileName" -------------
	var profileName ProfileName

	err = runtime.BindStyledParameterWithOptions("simple", "profileName", r.PathValue("profileName"), &profileName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentProfile(w, r, profileName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAgentProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateAgentProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "profileName" -------------
	var profileName ProfileName

	err = runtime.BindStyledParameterWithOptions("simple", "profileName", r.PathValue("profileName"), &profileName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAgentProfile(w, r, profileName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartAgentRun operation middleware
func (siw *ServerInterfaceWrapper) StartAgentRun(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartAgentRun(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOpenCodeBindings operation middleware
func (siw *ServerInterfaceWrapper) ListOpenCodeBindings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOpenCodeBindings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOpenCodeBinding operation middleware
func (siw *ServerInterfaceWrapper) CreateOpenCodeBinding(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOpenCodeBinding(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOpenCodeBinding operation middleware
func (siw *ServerInterfaceWrapper) DeleteOpenCodeBinding(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bindingName" -------------
	var bindingName BindingName

	err = runtime.BindStyledParameterWithOptions("simple", "bindingName", r.PathValue("bindingName"), &bindingName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bindingName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOpenCodeBinding(w, r, bindingName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpenCodeBinding operation middleware
func (siw *ServerInterfaceWrapper) GetOpenCodeBinding(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bindingName" -------------
	var bindingName BindingName

	err = runtime.BindStyledParameterWithOptions("simple", "bindingName", r.PathValue("bindingName"), &bindingName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bindingName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenCodeBinding(w, r, bindingName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOpenCodeBinding operation middleware
func (siw *ServerInterfaceWrapper) UpdateOpenCodeBinding(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bindingName" -------------
	var bindingName BindingName

	err = runtime.BindStyledParameterWithOptions("simple", "bindingName", r.PathValue("bindingName"), &bindingName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bindingName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOpenCodeBinding(w, r, bindingName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOpenCodeLaunch operation middleware
func (siw *ServerInterfaceWrapper) CreateOpenCodeLaunch(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOpenCodeLaunch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProviders operation middleware
func (siw *ServerInterfaceWrapper) ListProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProvider operation middleware
func (siw *ServerInterfaceWrapper) CreateProvider(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProvider(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProvider operation middleware
func (siw *ServerInterfaceWrapper) DeleteProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "providerName" -------------
	var providerName ProviderName

	err = runtime.BindStyledParameterWithOptions("simple", "providerName", r.PathValue("providerName"), &providerName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProvider(w, r, providerName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProvider operation middleware
func (siw *ServerInterfaceWrapper) GetProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "providerName" -------------
	var providerName ProviderName

	err = runtime.BindStyledParameterWithOptions("simple", "providerName", r.PathValue("providerName"), &providerName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProvider(w, r, providerName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProvider operation middleware
func (siw *ServerInterfaceWrapper) UpdateProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "providerName" -------------
	var providerName ProviderName

	err = runtime.BindStyledParameterWithOptions("simple", "providerName", r.PathValue("providerName"), &providerName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProvider(w, r, providerName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSessionsParams

	// ------------- Required query parameter "limit" -------------

	if paramValue := r.URL.Query().Get("limit"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReadSession operation middleware
func (siw *ServerInterfaceWrapper) ReadSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReadSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ContinueAgentRun operation middleware
func (siw *ServerInterfaceWrapper) ContinueAgentRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ContinueAgentRun(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/agent-profiles", wrapper.ListAgentProfiles)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/agent-profiles", wrapper.CreateAgentProfile)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/agent-profiles/{profileName}", wrapper.DeleteAgentProfile)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/agent-profiles/{profileName}", wrapper.GetAgentProfile)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/agent-profiles/{profileName}", wrapper.UpdateAgentProfile)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/agent-runs", wrapper.StartAgentRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/models", wrapper.ListModels)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/opencode-bindings", wrapper.ListOpenCodeBindings)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/opencode-bindings", wrapper.CreateOpenCodeBinding)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/opencode-bindings/{bindingName}", wrapper.DeleteOpenCodeBinding)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/opencode-bindings/{bindingName}", wrapper.GetOpenCodeBinding)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/opencode-bindings/{bindingName}", wrapper.UpdateOpenCodeBinding)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/opencode-launches", wrapper.CreateOpenCodeLaunch)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/providers", wrapper.ListProviders)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/providers", wrapper.CreateProvider)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/providers/{providerName}", wrapper.DeleteProvider)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/providers/{providerName}", wrapper.GetProvider)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/providers/{providerName}", wrapper.UpdateProvider)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions", wrapper.ListSessions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/{sessionId}", wrapper.ReadSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions/{sessionId}/agent-runs", wrapper.ContinueAgentRun)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x97XIbN5boq6D6TtWlfElKnpEziVz3hyM7iXbsWCXaNbUbeotg9yGJcRPoAGjKjItV",
	"eYedP/t6eZKtA6C/0c2mRNnxZP+4LLIbODhfON/8GIRinQgOXKvg4mOQUEnXoEGav75lPGJ8+SNdA/4Z",
	"gQolSzQTPLgI3nL2cwrkdQL8UkRA5vZhwukayCCRbE3llryH7ZDAeDkmM5EAD0UEozVlfHYyDoYBw4US",
	"qlfBMOBml2Be2nMYSPg5ZRKi4ELLFIaBClewpgjMmvGXwJd6FVw8HgZ6m+DLSkvGl8FuNwyupViwGDph",
	"T+wz7SCHAmEZ0SVw3QpxUtrpnhBvWARyH8jmoW40UzYb2v9JkWqQXbAXe94H+AkoxQS/ipqQu68Ii4Br",
	"tmAgycCA+vbt1fMTIkGnkkNEFlKsCSWJhA0TqSIzZV/8VqQ8mhEhSbgSCjhZCEko4XBLQsE3IBXFnVpO",
	"qHLA7n68Hb6qEsEVWLmg0Q38nILS+FcouAZu/kuTJGahAec0kWIew/r//UMhFj6WNvuThEVwEfyf00L2",
	"Tu236vTavvUcNGWxsntX0fmKxgsh1xARaWEgcxFtET0bGrPIbE4WlMWphHGwGwaXgi9iFn4OWG9AiVSG",
	"TsJCBwgZRKndG5BxTwyUV1yD5DR+IaWQnwHUtxw+JBBqiIgCuQFJACExsP0o9HfIhJ8Vg0KTBQJhIHrL",
	"aapXQrJf4HNA9SzVKxRmuw3J5AqZkHHDhiSUYOSdxmpsNIRbHTd/dnk90RETz1CvXor1mlrc0ihiuCCN",
	"r6VIQGqG8ragsYI6BO4tEsGCprFWJFUQES1ITFMergjl5Nnl9QhPRzWbx0AU7kiMKkdVkZR2+BhQuVRN",
	"zZVtQuUyXSOKSEKV20evoGMHAh8gTDWdx2D0koa12qtn8g+olHQbDIPU6Pwr+zKqrN0Q7+sMXX5gi51L",
	"6OiGFkHcp+AL3flTDsO7/EEx/weEGo9gaOou34zOLwxITPAJaM24RfUBxL5JuWZrGIlbvCcgW60gPt4I",
	"3uNlN3z+jof0NSbskgwv4yJRbj0EeZ3Y45FbId+jZRQxCaEWcltnVkedOkka7LEWEThpx6snoGEyMu8E",
	"dYzlGCf4zl78KM92NZqbvYdVbO2jv5fugsPrRXDx0x5Ml5a5gWUaU9lcbTfsv0g7L+7e1cB+yZS+cff9",
	"gZyKrxKxIIpuIHKqoIzjKutl3+D/cxXRHysOwrreqFMu32UfuVrx/ADSOk9ZrEeM95FQ9+IrEUHcFLPv",
	"0jjejn5OaYy2ZX4jGMaPCeNklhm5p+ajEdoiMwRivVfvFSLXJV5j8nrNtDmWtCgsjlc5FvB0jRRxT5UI",
	"0iJ0lZPvJ9+dWPaZj1kJVYVhPt9aDXV91aRNKIFqiJ7pJpKuJq/J11+dPSbmGUQWsoXSdJ3gOkgAilos",
	"ohpG+JVP5UVMJTHd+n2iH9I15aOFZMCjeJvDHtM5xGSwplsyBwLrRG9PvPoUfJzeV/586ihgXGmZhvix",
	"x55wb45UAiFbsJDMYUU3zFhNxXteUHmXU6ghXHEW0rjdo/UjQIoYWsEk+C2xX83x/lqx5WoUwwZi4twh",
	"Nmcx01vv2lqI+AYWHjS8EQJXWIAEHoIidENZnBksesVUdoyK6dRtLO2GQZpEe1kxpkqP7IOHc2NNOLn1",
	"mcsc6jBa44MSLnw8NywJUfkUrfJ+k/KS+9kp6lVhXYNSdAn7uPytAvnKPnrp/AqnCeMOK8fqW0TKUytz",
	"REEMoVZGeUh7KeTaeTD7EW6z03CQ11TStRobTYeonJ30MEnccVoRNdES6Pqy5Bv1V4sGEiJSnaSZh82J",
	"MgtCRGY2JERgg5i7IBo+aJJQqRVBG1xkSJkhP8xQFyVJFuJ49vxvxEUl3Psn4ymfmbdnpKy1yO0KOBE8",
	"3pI1aBpRTYmRDlBoIk5506LARZpEetV70adErJlhTDJzTuWMoB8nId7iczSOxS1EdhW9Agn4KRcGRxak",
	"/qaMJdA1ldon0K3aKUpDkGhmIWc5LniaYc7AnwGIXrMCjbTDZ1MegYy3eDqD+fKlnCqQQcbme29mi+g9",
	"nPdi08l3NghV8+KolAx1IlExCwEPifySxcLGZskZOSUzA+j45ctX2b0/IwsGcYQXdwwbyjWq0zBmiPYp",
	"HxgWtQzM+HJouJXRmISrlL9XQ4I0igHBOBmTiQmBKINTGpUYmkUKvfyMc3w8aCMTXpU9l5SHK+9XpQhG",
	"T7Yp6SYTqrn0mmrXlq9zfnV2jkrlgoZo9nAb6MlYpCGd5JS8fPkqu/HAb0jgCq8K7dp8IOOE3HVDKHxL",
	"sci7AOMapEwTDeXv50LEQLl9YCNsOObKv4Kjt+dy5KGENXCdK3Gr9Z5anBntaLTaDO3BS8smMEOxNxxs",
	"OQj/XDBkEbSDEZP4dAlbJVjL6/hOU5M1i7w9smaUyMGWLyzx4Ogl5Krd8odFwZi8+EBDHaPyN7KIQjQk",
	"eJ1f0jgeoijYu13hpdatm/FdvyHjltvH+2/cc8+ppoWFhTv3edM+ad/deXB5aYyQqkPRz8ioRyxLUWnk",
	"BWv+8yXqtKan4XH3ukz+3NxYddj+X5ixv8cFvb/pT67WaxcSpAsNMvfIeux+RBdhX/DzyA7DIbHWFtve",
	"b803Oeldqzxl6VGXSj26SPFGAvZ+Ec5staNEOBHUHDwb6/SKpv3Krqb6Qviy8lJ/OWnNU5/04NGkK6uM",
	"n2ZWqdV0S+AgS7JJlRIho8Y8ZXplebdEt0OC8I5Fq9nnCqnriN3PpRand2NS+y5hHB0m6/ohmi0icgSU",
	"naNWhp131R3kTGdXzshpdxRyTP5u/BvrBQwNMRZMovS4JzP7JIOJ2eSRlzM76T2pHC0HoBcXrRNPmAId",
	"b2K/RChvqYxsnqAmRGQRi9tD+aXKKA6EdpbIqhGObwRwuC3KGELBF2yZStqSnEnY32DbxNSz6ysUWVsK",
	"UElGjslECwkR2nRJTNFu/qDJIBYhjU8j2CCt+0j6nCp4Kz3m8rdUAXl78zKT9PwoCBPwKBGsR0ZteDcz",
	"p928MZa7z/U3n5evzJUU6XKV35sG+HFft90sd2mI5nPZe+pgn43yKlWarKkOV2T2nz/R0S/v8J+z0Tej",
	"d4/+NLuXDWM/8NgwlnCJFFqEIib43Ji85vE2K6MpZcyMw6PSJBFSQ3QPePx63DxUsN0wY32fhD4XHPbE",
	"Frzxv4YXGgm+P87Z7n6VmeFQ18t6mk22pBWePIJn4LIBMF6Oh2QafH/9hpyPH0+DkwPi7G9yznVZpVop",
	"Ey68TPSoWHgPR6p0vaaS/ULtBnmOqwVdz0GxJacalBVbCwUqv8pCRFP1XrnqKmt72DvYxTM00zEo9AcW",
	"ZJ3GmiUx2LUUWdEN2MWBI0EqVyd6v6b4JL8sjX+7x283uGzlmyu+EPfmGhpKoQo1poaE8TBOzT1fUc5G",
	"4yDCFrV0YUbKsOUGOrKaPhZ/+WwKc9IOPZdpXViwD3g91lFRRPAVidl78GdOewTmc1iGe3jgCJn2ghcc",
	"IzuWoHFcsEWTrMV12f/aMxy7z3N0C/uO7PWtDjt1bgiGe+qfnl1e37vKiaoRU1mtU77zESqbDi9jkmnh",
	"6N61Wmloz99FGeelH60ApO6bq1Zfpz8rNiIKPctA8o16IOCepQSNmvC+1QRHiVSUKxL6FRm44MYDxyX2",
	"OZeN7ysJ7bsnqKuOH551T5zgkIS0/9R3VGpOd2U6rckfWlKu0AD3eISX1yT/OivLMZa8qXSrWe8HqpBi",
	"3/04uKPsuBQC3mgOD2VBso0IqAb3RksOZjMbCigSCV3JysbZVbnuv4WDD9dtFpNvzdt969scf1f7R8rV",
	"/5VzFrDtp6iD4zB6XlOJd6gp67RAnLq6Ey4Ke9NWBDi+7yiBS+g2FjQ6Mnkyv7ib+cs4dF5qBo4Pd7Xq",
	"8YOy3zffXZJvzp/8lbjCdRLZVchApXMF+sRXHIhPtORMlaY89HO90lSn5cIixjUsQRq8oJ/UibFcG6eS",
	"efWwDy3GFj2CbeEPnvnrS63921sAi6hf/+JSt8W7jkPf2Z7wH7XFniCDLCyILjJV7yE6aQspXkvYMLj1",
	"lcrgeyRbKbHPOZ96Nh6PP/z7L49nJ2PyI2zABpLRj8KHvX7Z/eOITXPld1Rz2bvW8kuPTwb3jSv6FvhM",
	"JYstscZMJtrsv2GXczspNesdJTZZ7v7z4U61dxy+VS6UxWwOcnb9evKGnLo31OnH/N3dqbGERzLlajbu",
	"GQot792BioM0fRUZGaS99bbb8pUry/KxvhbaV/3zBj8mPF3PbUldtrUNxWdxtJ9TkFsymMNCSCAxWzN9",
	"KhaL7EquX6F+C8JWwiIUHVjLj3AYxu7g9e2xjTIbwN/Mar4ek2fxLd0qwgUf2eLK3379J5GgRLwprqY5",
	"Dd8Dj8bkexuShYhsGDVVZdXw7YCh9V/9zAUEFYmyGHB0MiQRSLbJCkqLOG2qQGYFkaY4iRKDApT0iCxo",
	"HCMsNnCc0fmW6ZVINW5sE2f2aOUA7/Fc0ootaTB8iLPpkD8xptsxlYxd0cskuZlY5YO/r0CvABEsU47k",
	"CVMpget4S2xTy1KCUi7XjK6nq98sFZzSULONKS+JYthfcZrrHguRFz+26lRKIe+CndAVUO6vXjT1jt5b",
	"vqiB9JkNEmhkLnnXn/zU5c4QRTbfYMvwTN0pikxvjdxVC14rxo0YArZmnGpbprqmSYJrZwGoHrWnL9y2",
	"JoHW8niRpXMFoq3Ku062YfXy69b5pRt3WOPn7hfLYrTLecGZfQ6xu2HPfr0mMPua87xQ9C7+7blHHbP7",
	"XihoZroCKxWXh/kupmatKMrNmvWLW8HWb7fG6Ps7zc9aupM1QjD4t8nrH4mVhfJVXUgHi1oN4pDGMbl6",
	"XjUFtC3GU2msD8lw4VuLlJsiOmNf75dtFnUlkGo1rXeKtpWdSGpPVpCsSRsfqi59OBKSLU0ttFkS0Xhs",
	"VBUTKQ5jFrO462rZxxsHkcMGyR6gfNiYBO3lw2Rm+znR2i8qMnhkWj9oGEKCMrcCeWil8Q9/mALjL6vE",
	"l9xAEtMQbF8ZfGDKcEfMlD5a+e996n6tIDxM3W8uCxmjNzJttgXoE9YA//3zl/7WiHdwDayl2JELHktq",
	"q6XYMdNctrVmm+B/JRyuxe5SI2ka1rUg7wESI0fOfSEbGqfwQIHM+xRE/vCJ6iD7apc7xyDrWXmHVS9f",
	"NvtwD2PKt6VwQDkQVop5kVPkSs14anp0K52sA2qjGyaqgCrxqeun5BoNJtdaeHJIH2qqtNmPMk6oJjFQ",
	"V12WdWKZsvginGKgsT6inco0UiyC0qSrrNcYCaSM/Ej4hx3jhAc2552LiIE6oDe1hHh/b2rvZtD6SofR",
	"b8L4EjnVdG4WrWq0Euchg/IcME/Co6XvrJ7ixqeaR9gZM8RW6tUk8s2bayPiRr8Ymww5yka7irTM87+R",
	"WanP27Su3qR8ZmrY8TRZQWNqgk5vbK84B4mHVGQ2yTpWUaomkxezp8TsnA9kw+fIo0e2Y3U0QTiMB6ce",
	"PSKDGR7r1PiyIxtamCG/TvmjR3Zhw42Shvri0SPygoYrMpm8yFFrQFCa8ojKiCykAYQMZmbBi1neyjAk",
	"s4hqejEjaFLjDi82ILf20xmJGTdtBpSULG7L6pQTu9qMVOISZKAAstPbpt8CcCo12ahccBF0j2TPYcm4",
	"cgX3LjDw1AZZ7IAzqhRb8mLQ3lU0m3JTe7VmWhGmLXmy4GJtHp9toO4bW5/yDFplWm4zxZqVpg4UXUN1",
	"op1a0QSe5k+EYg2qCHgmVK+c6nGh2mCCpFiLqOBGM3Lg2fVVMAw2IJVl3LPx4/GZiWwkwGnCgovgL+aj",
	"oRkdaGTGgV4e0LMEI0UoWXmbrUnJls14FdRGBf757KxjPtthc9laZxR5JrR1DyLaDYPzs8dt++UHOK2M",
	"mdsNgyf2NN0vVSf57fJq520GFnrMPriQlBTdpp9sY2/xxbvdMEiE8hCg2bXq5jyC0t+KaHs05Le3x+6q",
	"qtTNaatxweMH4YIuDqigkLgguyN9DyqWZlzelVvOz77Z/1I+nfIY7GWJlKm8Jot1cdhuWJf604+l0qKd",
	"vQGzlvUqFz43n9e4sDxLtyV6WjxyWp5Xu3vX4J9zj31fIbAFLRrfg1rn+1/KJ2Eeg1oWa/64DtoPWba6",
	"XSd4dfL3oB+SEmefV5K/JAJ/D/o+1E1SD3WbccYjEPj410V7OLTXdfHpmcwC3BjO8Emvi0/Nn/bMeTDN",
	"jc+x46XvfHuguWtcYGev1NIF5oaqWeVD6zkV02lccziQJdsAr6X10UK3voxy86OIQHN+MnnhHChr2ENU",
	"tuwJTRKgUu236bMn7B7WxK7KoPFAMqfugeyt+qSzO4lNw/szRQAf6DpxRr0y/8X/mcBXlve8IGW8TLlx",
	"7sjHqf12GlxMKxnaaTCcFqUN5usnT87g6/OzsxH8+Zv56PxxdD6if3381ej8/Kuvnjw5Pz87OzubBjv0",
	"6NyOhvLerew3uIeb4TN1uZ1pdtZpcPHRfqumqAGn5uTm5R8gjsU02L3b3X0zG5yYVub2HAzDkNwKGUfj",
	"BiyR4OAFxXyBOCrNj/bkKt98N/raeO2OYa0bb5b57df/VpkTbqQbvXDjg+fpuoqLPeXG7c44xIhawZsn",
	"3qKYpiotYDHl/HYetBVUdEnjbCBeNnILzEgtUyJgIvcroFnRrov7jd64SsMyElzDaJPJn5JwRaUC/f9T",
	"vRh97QP5E6r1e2tpG++wCjP37Bu62Khdq4eLELCzD+uheuRj2yHoegazwDxqfF/7oGMpruXWNZi6AHGl",
	"v3TKtbDz8YgplDGpI5cRbu+1JAN/m2UtrubTw+hN27j2Q4Ydmp2aHfGGejvm7yHW0KtFtMRQDqWWmfJf",
	"LSk36rXGgmppvwelS1fT4t6IkKcz8fcSFGqAViJNvSEqphz2RodqiHrQAFFL3vcTx4hae0SbbNHIIP9h",
	"I0V1TOxnO69+OP1YakHrETVqcudh3mz5R5r6BY4aJP/yY0eNIzUDDK2qoy2I9MCEOfs9SPuXGk26D707",
	"wkrHJ/lDRZbuc898Fs7L4kstHPjHDTHd89pxveKVkFOXEWRrpz6JDVSdJviZTKBaU36XTnRt2JlXHhn3",
	"XzpvMUtDu47kf3G2dcMcPfMHbAa+OdWxPodR9ePjSotyq1t1XfLSHkyZeTu0Oxyp1jbsz+9ItYBWIkmB",
	"0X3e03UxzOnhVEa9+PITK4tm23uT7Nf+VvQ/oLvk564W5qoIucmo5z842sM5KjHfwTm+4odN+7lFLQT+",
	"kp2jlvEJTWO5qg7aPKIHo8bZ70CSvzxX6I7U7fB/jkngh/J87nRVfFoGy3ydpIvR/sU9njuyJ14X5ekH",
	"nRmczCbPf8dowKKh7V8fFrMylEulxHHe9D7lc4gFX5rsjO2WLHVIQGQy7kOizLAwhDimSpPSEA4yWAul",
	"iYQQuLa59JO2DM2kmH5QE6r65JkPbJ2ufbMYtHB+CBk8/u3X/3p8dlb8oLcZzVD83rWZzdD9W9d2n+Di",
	"8dmZacpwf/nGODRG3HthU+9ZQgaI5IQuGafuR4SeZ7MptSBnbfDaKRLB0JfaLIN35gHvIS8S3xAP311i",
	"DwyR6UAoIab4iaTgS0q2Ghcip202Kr8pHCXxzfm7Kr3lSvAOSU5iurWpuBVTWkgzf6f682iEKpPfX6Dw",
	"KDO92DN2wY5TyECe8ry2pjRWQGncTCTAXWo/K0l30/Ztq88G9qTrx1N+5X7mIftte0VYZLROsRnwSLki",
	"fzKLBIesvsb2s0hzdNtRiQffmvJ+15UgZATyYsofj/0lOgOjU+VaVaGITqb8z8Urtrc+f2dmUWR+Sn+G",
	"4M5OpvwvY/IfIIX5US8hofbLdg7KbNKIg3TKzy0VzHoXJTya4xoM1tapYnLBOFMrUFP+ZFzBjUeF3gCN",
	"HIsdbJZM8nEjPXSFt1joLlUn//egmpPDi0oKzqnKydMyf7OSkFg6/c5LS84/w+/YZ9N8qj+uf28liixb",
	"12EDS7VMhCq/hBJvCYJoBUem/KSrumVPp0176eHEKCTrwlcayFy9n601zMAuVxkWhYnZ+csVh5NG5w5V",
	"ZKbKNYKzp5VSRKaIpu+BV7t5yMD8iYYjE3LKvYrPBM5t5+EoXAmFnB4NSQQJ2Pij4Fl7UyJiFm69Ztml",
	"U1ilGsb7KZZ/ufrHB6pGnKQSyG+//vP+RYD/W4V3Fz/wE+vXm2y+ivm5WbYodx+6Hl5TSEd1xY4x3YGK",
	"uGlzMuWc8SUaXUgo80uV2roe+KJrUnZD1wrbdbAEPRJyZAO0J2aklDBt7yumip/znPLjBEizJmrKi6I9",
	"63c2ux1b1buZSmd+edXjH95ATI2J6zxW0wbrkDl3PfjBMEhlHFwEp0YxuV0aN4GpqBSyaP22poLNd4WA",
	"m3h/D7Nw20pwN71Em4fgEWFcJRBqlITCqygWyT2H5hKvKMer6eXLV23JDDK4vHn7/KRYrQgjtC7na0XZ",
	"s2qt0r916UbVmkFAnlLM0meqnD8r58rcdt5UWRuGO+oaSxWt5RJHt4urcNy92/1PAAAA//9B3+KiAY4A",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
