//go:build go1.22

// Package agentapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260404004943-9ea3cc79a4c7 DO NOT EDIT.
package agentapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AgentProfileRegularExecutionSettingsMode.
const (
	Regular AgentProfileRegularExecutionSettingsMode = "regular"
)

// Valid indicates whether the value is a known member of the AgentProfileRegularExecutionSettingsMode enum.
func (e AgentProfileRegularExecutionSettingsMode) Valid() bool {
	switch e {
	case Regular:
		return true
	default:
		return false
	}
}

// Defines values for AgentStreamContentRole.
const (
	Model AgentStreamContentRole = "model"
	User  AgentStreamContentRole = "user"
)

// Valid indicates whether the value is a known member of the AgentStreamContentRole enum.
func (e AgentStreamContentRole) Valid() bool {
	switch e {
	case Model:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatusEventStatus.
const (
	Active SessionStatusEventStatus = "active"
	Idle   SessionStatusEventStatus = "idle"
)

// Valid indicates whether the value is a known member of the SessionStatusEventStatus enum.
func (e SessionStatusEventStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Idle:
		return true
	default:
		return false
	}
}

// ACPStdioAgentCommand Command defaults used to launch an ACP-compatible stdio agent.
type ACPStdioAgentCommand struct {
	// Args Command arguments passed to the ACP-compatible stdio agent executable.
	Args *[]string `json:"args,omitempty"`

	// Command Command executable to launch the ACP-compatible stdio agent.
	Command string `json:"command"`
}

// AgentProfileACPStdioExecutionSettings Runtime-owned execution defaults for ACP-compatible stdio profile execution.
type AgentProfileACPStdioExecutionSettings struct {
	// AgentCommand Command defaults used to launch an ACP-compatible stdio agent.
	AgentCommand ACPStdioAgentCommand `json:"agentCommand"`

	// Cwd Optional working directory used to launch the ACP stdio agent.
	Cwd *string `json:"cwd,omitempty"`

	// Mode Execution mode for ACP-compatible stdio profiles.
	Mode string `json:"mode"`
}

// AgentProfileExecutionSettings defines model for AgentProfileExecutionSettings.
type AgentProfileExecutionSettings struct {
	union json.RawMessage
}

// AgentProfileListResponse List of saved agent profiles.
type AgentProfileListResponse struct {
	Profiles []AgentProfileResponse `json:"profiles"`
}

// AgentProfileRegularExecutionSettings Runtime-owned execution defaults for built-in profile execution.
type AgentProfileRegularExecutionSettings struct {
	// DefaultModel Fully-qualified default model in `provider/model-name` form.
	DefaultModel string `json:"defaultModel"`

	// Mode Execution mode. Omit for regular built-in execution.
	Mode *AgentProfileRegularExecutionSettingsMode `json:"mode,omitempty"`
}

// AgentProfileRegularExecutionSettingsMode Execution mode. Omit for regular built-in execution.
type AgentProfileRegularExecutionSettingsMode string

// AgentProfileResponse A saved agent profile as returned by the API.
type AgentProfileResponse struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"createdAt"`

	// DisplayName Human-friendly profile label (may be empty).
	DisplayName       string                        `json:"displayName"`
	ExecutionSettings AgentProfileExecutionSettings `json:"executionSettings"`

	// Instructions Profile-specific behavior instructions.
	Instructions string `json:"instructions"`

	// Name Unique technical profile name (primary key).
	Name string `json:"name"`

	// Role Profile role describing high-level responsibility.
	Role string `json:"role"`

	// ToolRefs Tool references available to this profile.
	ToolRefs []string `json:"toolRefs"`

	// UpdatedAt ISO 8601 last-update timestamp.
	UpdatedAt time.Time `json:"updatedAt"`
}

// AgentRunRequest defines model for AgentRunRequest.
type AgentRunRequest struct {
	// Message User message for `POST /agent-runs` / continue run: text parts (always user role; not sent by clients).
	Message UserMessageContent `json:"message"`

	// ProfileName Name of the saved agent profile whose execution settings will be used for this run.
	ProfileName string `json:"profileName"`
}

// AgentStreamContent Model output body on streamed `agent` events: text parts and optional `role` (mapped from ADK session events).
// `parts` may be empty when only metadata is present.
type AgentStreamContent struct {
	// Parts May be empty when only metadata is present; omitting `content` entirely is allowed when there is no body.
	Parts []AgentStreamPart `json:"parts"`

	// Role Producer of the message; may be omitted when not set on the underlying event.
	Role *AgentStreamContentRole `json:"role,omitempty"`
}

// AgentStreamContentRole Producer of the message; may be omitted when not set on the underlying event.
type AgentStreamContentRole string

// AgentStreamEvent Carries a slice of ADK `session.Event` / `model.LLMResponse` fields relevant to clients
// (text streaming, partial chunks, completion). Servers may add optional ids or metadata.
type AgentStreamEvent struct {
	Author *string `json:"author,omitempty"`
	Branch *string `json:"branch,omitempty"`

	// Content Model output body on streamed `agent` events: text parts and optional `role` (mapped from ADK session events).
	// `parts` may be empty when only metadata is present.
	Content *AgentStreamContent `json:"content,omitempty"`

	// ErrorCode Present when the agent surfaced an error on the ADK session event / LLM response.
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	Event        string  `json:"event"`
	Id           *string `json:"id,omitempty"`
	Interrupted  *bool   `json:"interrupted,omitempty"`
	InvocationId *string `json:"invocationId,omitempty"`

	// Partial Incremental model output; when false and `turnComplete` is true, chunk is final for the turn.
	Partial              *bool                  `json:"partial,omitempty"`
	TurnComplete         *bool                  `json:"turnComplete,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// AgentStreamPart A segment in streamed agent output. Exactly one of text, toolCall, or toolResult is present.
type AgentStreamPart struct {
	Text *string `json:"text,omitempty"`

	// ToolCall Tool invocation requested by the model.
	ToolCall *ToolCallData `json:"toolCall,omitempty"`

	// ToolResult Result returned by a tool invocation.
	ToolResult *ToolResultData `json:"toolResult,omitempty"`
}

// CreateAgentProfileRequest Request body for creating a saved agent profile.
type CreateAgentProfileRequest struct {
	// DisplayName Optional human-friendly profile label.
	DisplayName       *string                       `json:"displayName,omitempty"`
	ExecutionSettings AgentProfileExecutionSettings `json:"executionSettings"`

	// Instructions Profile-specific behavior instructions.
	Instructions string `json:"instructions"`

	// Name Unique technical profile name (primary key). Immutable after creation.
	Name string `json:"name"`

	// Role Profile role describing high-level responsibility.
	Role string `json:"role"`

	// ToolRefs Tool references available to this profile.
	ToolRefs *[]string `json:"toolRefs,omitempty"`
}

// CreateOpenCodeBindingRequest Request body for creating an OpenCode binding.
type CreateOpenCodeBindingRequest struct {
	// AgentCommand OpenCode command defaults used to launch ACP.
	AgentCommand OpenCodeAgentCommand `json:"agentCommand"`

	// Cwd Optional working directory used for OpenCode launch.
	Cwd *string `json:"cwd,omitempty"`

	// LaunchOptions OpenCode launch defaults.
	LaunchOptions OpenCodeLaunchOptions `json:"launchOptions"`

	// Name Unique technical binding name (primary key).
	Name string `json:"name"`

	// ProfileName Name of the saved general profile associated with this binding.
	ProfileName string `json:"profileName"`
}

// CreateOpenCodeLaunchRequest Launch input selecting saved profile and optional binding.
type CreateOpenCodeLaunchRequest struct {
	// BindingName Optional saved binding selector. When omitted, the first binding for the profile is used.
	BindingName *string `json:"bindingName,omitempty"`

	// ProfileName Saved profile selector.
	ProfileName string `json:"profileName"`

	// Prompt User prompt forwarded to OpenCode launch flow.
	Prompt string `json:"prompt"`
}

// CreateProviderRequest Request body for creating a new provider configuration.
type CreateProviderRequest struct {
	// ApiKey API key for authentication. Stored in plaintext (local/dev use).
	ApiKey string `json:"apiKey"`

	// BaseUrl Base URL of the provider API endpoint.
	BaseUrl string `json:"baseUrl"`

	// DisplayName Optional human-friendly label.
	DisplayName *string `json:"displayName,omitempty"`

	// Models Models available through this provider.
	Models *[]ModelConfig `json:"models,omitempty"`

	// Name Unique technical name (primary key). Must match `^[a-z][a-z0-9-]*$`. Immutable after creation.
	Name string `json:"name"`

	// Type Provider protocol type. Only `openai-compatible` is supported. Immutable after creation.
	Type string `json:"type"`
}

// DoneEvent defines model for DoneEvent.
type DoneEvent struct {
	Event string `json:"event"`
}

// ModelConfig A model available through a provider.
type ModelConfig struct {
	// DisplayName Optional human-friendly label (e.g., "GPT 4.1").
	DisplayName *string `json:"displayName,omitempty"`

	// Name Technical model identifier (e.g., "gpt-4.1").
	Name string `json:"name"`

	// Summarization Designates this model for summarization tasks (e.g. generating session titles). If multiple models have this enabled, the first one found is used.
	Summarization *bool `json:"summarization,omitempty"`
}

// ModelInfo A model available across providers, including the provider name for fully-qualified identification.
type ModelInfo struct {
	// DisplayName Optional human-friendly label.
	DisplayName *string `json:"displayName,omitempty"`

	// Name Technical model identifier (e.g., "gpt-4.1").
	Name string `json:"name"`

	// Provider Provider name (prefix in fully-qualified model names like `provider/model-name`).
	Provider string `json:"provider"`
}

// ModelListResponse List of available models across all providers.
type ModelListResponse struct {
	Models []ModelInfo `json:"models"`
}

// OpenCodeAgentCommand OpenCode command defaults used to launch ACP.
type OpenCodeAgentCommand struct {
	// Args Command arguments passed as-is to the OpenCode executable.
	Args []string `json:"args"`

	// Command Command executable to run OpenCode.
	Command string `json:"command"`
}

// OpenCodeBindingListResponse List of saved OpenCode bindings.
type OpenCodeBindingListResponse struct {
	Bindings []OpenCodeBindingResponse `json:"bindings"`
}

// OpenCodeBindingResponse A saved OpenCode binding as returned by the API.
type OpenCodeBindingResponse struct {
	// AgentCommand OpenCode command defaults used to launch ACP.
	AgentCommand OpenCodeAgentCommand `json:"agentCommand"`
	CreatedAt    time.Time            `json:"createdAt"`
	Cwd          string               `json:"cwd"`

	// LaunchOptions OpenCode launch defaults.
	LaunchOptions OpenCodeLaunchOptions `json:"launchOptions"`
	Name          string                `json:"name"`
	ProfileName   string                `json:"profileName"`
	UpdatedAt     time.Time             `json:"updatedAt"`
}

// OpenCodeLaunchOptions OpenCode launch defaults.
type OpenCodeLaunchOptions struct {
	// Transport ACP transport mode. Only `stdio` is supported.
	Transport string `json:"transport"`
}

// OpenCodeLaunchResponse Result of a launched OpenCode coding run.
type OpenCodeLaunchResponse struct {
	BindingName  string                 `json:"bindingName"`
	ProfileName  string                 `json:"profileName"`
	PromptResult map[string]interface{} `json:"promptResult"`
	SessionId    string                 `json:"sessionId"`
	Updates      []OpenCodeLaunchUpdate `json:"updates"`
}

// OpenCodeLaunchUpdate Parsed ACP session/update notification from launch execution.
type OpenCodeLaunchUpdate struct {
	Payload   map[string]interface{} `json:"payload"`
	SessionId string                 `json:"sessionId"`
	Type      string                 `json:"type"`
}

// ProblemDetails RFC 9457 problem details (subset).
type ProblemDetails struct {
	Detail               *string                `json:"detail,omitempty"`
	Instance             *string                `json:"instance,omitempty"`
	Status               *int                   `json:"status,omitempty"`
	Title                *string                `json:"title,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ProviderListResponse List of provider configurations.
type ProviderListResponse struct {
	Providers []ProviderResponse `json:"providers"`
}

// ProviderResponse A provider configuration as returned by the API (API key is masked).
type ProviderResponse struct {
	// ApiKeyPreview Masked API key preview (e.g. `...xYz1`). Never the full key.
	ApiKeyPreview string `json:"apiKeyPreview"`

	// BaseUrl Base URL of the provider API endpoint.
	BaseUrl string `json:"baseUrl"`

	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"createdAt"`

	// DisplayName Human-friendly label (may be empty).
	DisplayName *string `json:"displayName,omitempty"`

	// Models Models available through this provider.
	Models []ModelConfig `json:"models"`

	// Name Unique technical name (primary key).
	Name string `json:"name"`

	// Type Provider protocol type.
	Type string `json:"type"`

	// UpdatedAt ISO 8601 last-update timestamp.
	UpdatedAt time.Time `json:"updatedAt"`
}

// SessionBoundEvent defines model for SessionBoundEvent.
type SessionBoundEvent struct {
	Event string `json:"event"`

	// SessionId Use this id for `POST /sessions/{sessionId}/agent-runs`.
	SessionId string `json:"sessionId"`
}

// SessionListResponse defines model for SessionListResponse.
type SessionListResponse struct {
	Sessions []SessionMetadata `json:"sessions"`

	// Total Total number of sessions matching the query (before limit/offset).
	Total int `json:"total"`
}

// SessionMetadata defines model for SessionMetadata.
type SessionMetadata struct {
	CreatedAt time.Time `json:"createdAt"`
	SessionId string    `json:"sessionId"`

	// Title Session title. Always non-empty — resolved by the backend. Generated via LLM summarization (if a summarization model is designated), derived from the first user message, or a date-based fallback for sessions without a stored title.
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// SessionStatusEvent defines model for SessionStatusEvent.
type SessionStatusEvent struct {
	Event string `json:"event"`

	// Status Whether a run is currently in progress for this session.
	Status SessionStatusEventStatus `json:"status"`
}

// SessionStatusEventStatus Whether a run is currently in progress for this session.
type SessionStatusEventStatus string

// StreamErrorEvent defines model for StreamErrorEvent.
type StreamErrorEvent struct {
	Code  *string `json:"code,omitempty"`
	Event string  `json:"event"`

	// Message Human-readable failure; after this, the stream may end.
	Message string `json:"message"`
}

// StreamEvent defines model for StreamEvent.
type StreamEvent struct {
	union json.RawMessage
}

// ToolCallData Tool invocation requested by the model.
type ToolCallData struct {
	// Args Arguments passed to the tool (JSON object).
	Args *map[string]interface{} `json:"args,omitempty"`

	// Id Unique call ID matching the tool result.
	Id string `json:"id"`

	// Name Tool function name.
	Name string `json:"name"`
}

// ToolResultData Result returned by a tool invocation.
type ToolResultData struct {
	// Id Call ID matching the original tool call.
	Id string `json:"id"`

	// Name Tool function name.
	Name string `json:"name"`

	// Response Tool output (JSON object).
	Response *map[string]interface{} `json:"response,omitempty"`
}

// UpdateAgentProfileRequest Request body for updating a saved agent profile. `name` is immutable and not accepted here.
type UpdateAgentProfileRequest struct {
	// DisplayName Human-friendly profile label.
	DisplayName       *string                       `json:"displayName,omitempty"`
	ExecutionSettings AgentProfileExecutionSettings `json:"executionSettings"`

	// Instructions Profile-specific behavior instructions.
	Instructions string `json:"instructions"`

	// Role Profile role describing high-level responsibility.
	Role string `json:"role"`

	// ToolRefs Tool references available to this profile. Replaces the existing list.
	ToolRefs *[]string `json:"toolRefs,omitempty"`
}

// UpdateOpenCodeBindingRequest Request body for updating mutable OpenCode binding fields.
type UpdateOpenCodeBindingRequest struct {
	// AgentCommand OpenCode command defaults used to launch ACP.
	AgentCommand OpenCodeAgentCommand `json:"agentCommand"`

	// Cwd Working directory used for OpenCode launch.
	Cwd *string `json:"cwd,omitempty"`

	// LaunchOptions OpenCode launch defaults.
	LaunchOptions OpenCodeLaunchOptions `json:"launchOptions"`
}

// UpdateProviderRequest Request body for updating a provider configuration. `name` and `type` are immutable and not accepted here.
type UpdateProviderRequest struct {
	// ApiKey API key for authentication. Omit to keep the current value.
	ApiKey *string `json:"apiKey,omitempty"`

	// BaseUrl Base URL of the provider API endpoint.
	BaseUrl string `json:"baseUrl"`

	// DisplayName Human-friendly label.
	DisplayName *string `json:"displayName,omitempty"`

	// Models Models available through this provider. Replaces the existing list.
	Models *[]ModelConfig `json:"models,omitempty"`
}

// UserMessageContent User message for `POST /agent-runs` / continue run: text parts (always user role; not sent by clients).
type UserMessageContent struct {
	// Parts Must contain at least one segment with non-empty text after server-side validation; empty lists are rejected for POST bodies.
	Parts []UserMessagePart `json:"parts"`
}

// UserMessagePart Single text segment in a user message (request body).
type UserMessagePart struct {
	Text string `json:"text"`
}

// BindingName defines model for BindingName.
type BindingName = string

// ProfileName defines model for ProfileName.
type ProfileName = string

// ProviderName defines model for ProviderName.
type ProviderName = string

// SessionId defines model for SessionId.
type SessionId = string

// BadRequest RFC 9457 problem details (subset).
type BadRequest = ProblemDetails

// Conflict RFC 9457 problem details (subset).
type Conflict = ProblemDetails

// InternalError RFC 9457 problem details (subset).
type InternalError = ProblemDetails

// NotFound RFC 9457 problem details (subset).
type NotFound = ProblemDetails

// Unauthorized RFC 9457 problem details (subset).
type Unauthorized = ProblemDetails

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	// Limit Maximum number of sessions to return (1–100).
	Limit int `form:"limit" json:"limit"`

	// Offset Number of sessions to skip (for pagination). Defaults to 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateAgentProfileJSONRequestBody defines body for CreateAgentProfile for application/json ContentType.
type CreateAgentProfileJSONRequestBody = CreateAgentProfileRequest

// UpdateAgentProfileJSONRequestBody defines body for UpdateAgentProfile for application/json ContentType.
type UpdateAgentProfileJSONRequestBody = UpdateAgentProfileRequest

// StartAgentRunJSONRequestBody defines body for StartAgentRun for application/json ContentType.
type StartAgentRunJSONRequestBody = AgentRunRequest

// CreateProviderJSONRequestBody defines body for CreateProvider for application/json ContentType.
type CreateProviderJSONRequestBody = CreateProviderRequest

// UpdateProviderJSONRequestBody defines body for UpdateProvider for application/json ContentType.
type UpdateProviderJSONRequestBody = UpdateProviderRequest

// ContinueAgentRunJSONRequestBody defines body for ContinueAgentRun for application/json ContentType.
type ContinueAgentRunJSONRequestBody = AgentRunRequest

// Getter for additional properties for AgentStreamEvent. Returns the specified
// element and whether it was found
func (a AgentStreamEvent) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for AgentStreamEvent
func (a *AgentStreamEvent) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for AgentStreamEvent to handle AdditionalProperties
func (a *AgentStreamEvent) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["author"]; found {
		err = json.Unmarshal(raw, &a.Author)
		if err != nil {
			return fmt.Errorf("error reading 'author': %w", err)
		}
		delete(object, "author")
	}

	if raw, found := object["branch"]; found {
		err = json.Unmarshal(raw, &a.Branch)
		if err != nil {
			return fmt.Errorf("error reading 'branch': %w", err)
		}
		delete(object, "branch")
	}

	if raw, found := object["content"]; found {
		err = json.Unmarshal(raw, &a.Content)
		if err != nil {
			return fmt.Errorf("error reading 'content': %w", err)
		}
		delete(object, "content")
	}

	if raw, found := object["errorCode"]; found {
		err = json.Unmarshal(raw, &a.ErrorCode)
		if err != nil {
			return fmt.Errorf("error reading 'errorCode': %w", err)
		}
		delete(object, "errorCode")
	}

	if raw, found := object["errorMessage"]; found {
		err = json.Unmarshal(raw, &a.ErrorMessage)
		if err != nil {
			return fmt.Errorf("error reading 'errorMessage': %w", err)
		}
		delete(object, "errorMessage")
	}

	if raw, found := object["event"]; found {
		err = json.Unmarshal(raw, &a.Event)
		if err != nil {
			return fmt.Errorf("error reading 'event': %w", err)
		}
		delete(object, "event")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["interrupted"]; found {
		err = json.Unmarshal(raw, &a.Interrupted)
		if err != nil {
			return fmt.Errorf("error reading 'interrupted': %w", err)
		}
		delete(object, "interrupted")
	}

	if raw, found := object["invocationId"]; found {
		err = json.Unmarshal(raw, &a.InvocationId)
		if err != nil {
			return fmt.Errorf("error reading 'invocationId': %w", err)
		}
		delete(object, "invocationId")
	}

	if raw, found := object["partial"]; found {
		err = json.Unmarshal(raw, &a.Partial)
		if err != nil {
			return fmt.Errorf("error reading 'partial': %w", err)
		}
		delete(object, "partial")
	}

	if raw, found := object["turnComplete"]; found {
		err = json.Unmarshal(raw, &a.TurnComplete)
		if err != nil {
			return fmt.Errorf("error reading 'turnComplete': %w", err)
		}
		delete(object, "turnComplete")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for AgentStreamEvent to handle AdditionalProperties
func (a AgentStreamEvent) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Author != nil {
		object["author"], err = json.Marshal(a.Author)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'author': %w", err)
		}
	}

	if a.Branch != nil {
		object["branch"], err = json.Marshal(a.Branch)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'branch': %w", err)
		}
	}

	if a.Content != nil {
		object["content"], err = json.Marshal(a.Content)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'content': %w", err)
		}
	}

	if a.ErrorCode != nil {
		object["errorCode"], err = json.Marshal(a.ErrorCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'errorCode': %w", err)
		}
	}

	if a.ErrorMessage != nil {
		object["errorMessage"], err = json.Marshal(a.ErrorMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'errorMessage': %w", err)
		}
	}

	object["event"], err = json.Marshal(a.Event)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'event': %w", err)
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Interrupted != nil {
		object["interrupted"], err = json.Marshal(a.Interrupted)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'interrupted': %w", err)
		}
	}

	if a.InvocationId != nil {
		object["invocationId"], err = json.Marshal(a.InvocationId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'invocationId': %w", err)
		}
	}

	if a.Partial != nil {
		object["partial"], err = json.Marshal(a.Partial)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'partial': %w", err)
		}
	}

	if a.TurnComplete != nil {
		object["turnComplete"], err = json.Marshal(a.TurnComplete)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'turnComplete': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ProblemDetails. Returns the specified
// element and whether it was found
func (a ProblemDetails) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemDetails
func (a *ProblemDetails) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a *ProblemDetails) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a ProblemDetails) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsAgentProfileRegularExecutionSettings returns the union data inside the AgentProfileExecutionSettings as a AgentProfileRegularExecutionSettings
func (t AgentProfileExecutionSettings) AsAgentProfileRegularExecutionSettings() (AgentProfileRegularExecutionSettings, error) {
	var body AgentProfileRegularExecutionSettings
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentProfileRegularExecutionSettings overwrites any union data inside the AgentProfileExecutionSettings as the provided AgentProfileRegularExecutionSettings
func (t *AgentProfileExecutionSettings) FromAgentProfileRegularExecutionSettings(v AgentProfileRegularExecutionSettings) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentProfileRegularExecutionSettings performs a merge with any union data inside the AgentProfileExecutionSettings, using the provided AgentProfileRegularExecutionSettings
func (t *AgentProfileExecutionSettings) MergeAgentProfileRegularExecutionSettings(v AgentProfileRegularExecutionSettings) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAgentProfileACPStdioExecutionSettings returns the union data inside the AgentProfileExecutionSettings as a AgentProfileACPStdioExecutionSettings
func (t AgentProfileExecutionSettings) AsAgentProfileACPStdioExecutionSettings() (AgentProfileACPStdioExecutionSettings, error) {
	var body AgentProfileACPStdioExecutionSettings
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentProfileACPStdioExecutionSettings overwrites any union data inside the AgentProfileExecutionSettings as the provided AgentProfileACPStdioExecutionSettings
func (t *AgentProfileExecutionSettings) FromAgentProfileACPStdioExecutionSettings(v AgentProfileACPStdioExecutionSettings) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentProfileACPStdioExecutionSettings performs a merge with any union data inside the AgentProfileExecutionSettings, using the provided AgentProfileACPStdioExecutionSettings
func (t *AgentProfileExecutionSettings) MergeAgentProfileACPStdioExecutionSettings(v AgentProfileACPStdioExecutionSettings) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AgentProfileExecutionSettings) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AgentProfileExecutionSettings) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSessionBoundEvent returns the union data inside the StreamEvent as a SessionBoundEvent
func (t StreamEvent) AsSessionBoundEvent() (SessionBoundEvent, error) {
	var body SessionBoundEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSessionBoundEvent overwrites any union data inside the StreamEvent as the provided SessionBoundEvent
func (t *StreamEvent) FromSessionBoundEvent(v SessionBoundEvent) error {
	v.Event = "sessionBound"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSessionBoundEvent performs a merge with any union data inside the StreamEvent, using the provided SessionBoundEvent
func (t *StreamEvent) MergeSessionBoundEvent(v SessionBoundEvent) error {
	v.Event = "sessionBound"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSessionStatusEvent returns the union data inside the StreamEvent as a SessionStatusEvent
func (t StreamEvent) AsSessionStatusEvent() (SessionStatusEvent, error) {
	var body SessionStatusEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSessionStatusEvent overwrites any union data inside the StreamEvent as the provided SessionStatusEvent
func (t *StreamEvent) FromSessionStatusEvent(v SessionStatusEvent) error {
	v.Event = "sessionStatus"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSessionStatusEvent performs a merge with any union data inside the StreamEvent, using the provided SessionStatusEvent
func (t *StreamEvent) MergeSessionStatusEvent(v SessionStatusEvent) error {
	v.Event = "sessionStatus"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAgentStreamEvent returns the union data inside the StreamEvent as a AgentStreamEvent
func (t StreamEvent) AsAgentStreamEvent() (AgentStreamEvent, error) {
	var body AgentStreamEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentStreamEvent overwrites any union data inside the StreamEvent as the provided AgentStreamEvent
func (t *StreamEvent) FromAgentStreamEvent(v AgentStreamEvent) error {
	v.Event = "agent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentStreamEvent performs a merge with any union data inside the StreamEvent, using the provided AgentStreamEvent
func (t *StreamEvent) MergeAgentStreamEvent(v AgentStreamEvent) error {
	v.Event = "agent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStreamErrorEvent returns the union data inside the StreamEvent as a StreamErrorEvent
func (t StreamEvent) AsStreamErrorEvent() (StreamErrorEvent, error) {
	var body StreamErrorEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreamErrorEvent overwrites any union data inside the StreamEvent as the provided StreamErrorEvent
func (t *StreamEvent) FromStreamErrorEvent(v StreamErrorEvent) error {
	v.Event = "error"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStreamErrorEvent performs a merge with any union data inside the StreamEvent, using the provided StreamErrorEvent
func (t *StreamEvent) MergeStreamErrorEvent(v StreamErrorEvent) error {
	v.Event = "error"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDoneEvent returns the union data inside the StreamEvent as a DoneEvent
func (t StreamEvent) AsDoneEvent() (DoneEvent, error) {
	var body DoneEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDoneEvent overwrites any union data inside the StreamEvent as the provided DoneEvent
func (t *StreamEvent) FromDoneEvent(v DoneEvent) error {
	v.Event = "done"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDoneEvent performs a merge with any union data inside the StreamEvent, using the provided DoneEvent
func (t *StreamEvent) MergeDoneEvent(v DoneEvent) error {
	v.Event = "done"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StreamEvent) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"event"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t StreamEvent) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "agent":
		return t.AsAgentStreamEvent()
	case "done":
		return t.AsDoneEvent()
	case "error":
		return t.AsStreamErrorEvent()
	case "sessionBound":
		return t.AsSessionBoundEvent()
	case "sessionStatus":
		return t.AsSessionStatusEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t StreamEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StreamEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all saved agent profiles
	// (GET /agent-profiles)
	ListAgentProfiles(w http.ResponseWriter, r *http.Request)
	// Create a new saved agent profile
	// (POST /agent-profiles)
	CreateAgentProfile(w http.ResponseWriter, r *http.Request)
	// Delete a saved agent profile by name
	// (DELETE /agent-profiles/{profileName})
	DeleteAgentProfile(w http.ResponseWriter, r *http.Request, profileName ProfileName)
	// Get a saved agent profile by name
	// (GET /agent-profiles/{profileName})
	GetAgentProfile(w http.ResponseWriter, r *http.Request, profileName ProfileName)
	// Update mutable fields for a saved agent profile
	// (PUT /agent-profiles/{profileName})
	UpdateAgentProfile(w http.ResponseWriter, r *http.Request, profileName ProfileName)
	// Start a new agent run
	// (POST /agent-runs)
	StartAgentRun(w http.ResponseWriter, r *http.Request)
	// List all available models across all providers
	// (GET /models)
	ListModels(w http.ResponseWriter, r *http.Request)
	// List all provider configurations
	// (GET /providers)
	ListProviders(w http.ResponseWriter, r *http.Request)
	// Create a new provider configuration
	// (POST /providers)
	CreateProvider(w http.ResponseWriter, r *http.Request)
	// Delete a provider configuration by name
	// (DELETE /providers/{providerName})
	DeleteProvider(w http.ResponseWriter, r *http.Request, providerName ProviderName)
	// Get a provider configuration by name
	// (GET /providers/{providerName})
	GetProvider(w http.ResponseWriter, r *http.Request, providerName ProviderName)
	// Update a provider configuration by name
	// (PUT /providers/{providerName})
	UpdateProvider(w http.ResponseWriter, r *http.Request, providerName ProviderName)
	// List sessions for the authenticated user
	// (GET /sessions)
	ListSessions(w http.ResponseWriter, r *http.Request, params ListSessionsParams)
	// Read session events (replay history and optionally tail live run)
	// (GET /sessions/{sessionId})
	ReadSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Continue an agent run for an existing session
	// (POST /sessions/{sessionId}/agent-runs)
	ContinueAgentRun(w http.ResponseWriter, r *http.Request, sessionId SessionId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAgentProfiles operation middleware
func (siw *ServerInterfaceWrapper) ListAgentProfiles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgentProfiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAgentProfile operation middleware
func (siw *ServerInterfaceWrapper) CreateAgentProfile(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAgentProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAgentProfile operation middleware
func (siw *ServerInterfaceWrapper) DeleteAgentProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "profileName" -------------
	var profileName ProfileName

	err = runtime.BindStyledParameterWithOptions("simple", "profileName", r.PathValue("profileName"), &profileName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAgentProfile(w, r, profileName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgentProfile operation middleware
func (siw *ServerInterfaceWrapper) GetAgentProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "profileName" -------------
	var profileName ProfileName

	err = runtime.BindStyledParameterWithOptions("simple", "profileName", r.PathValue("profileName"), &profileName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentProfile(w, r, profileName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAgentProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateAgentProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "profileName" -------------
	var profileName ProfileName

	err = runtime.BindStyledParameterWithOptions("simple", "profileName", r.PathValue("profileName"), &profileName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAgentProfile(w, r, profileName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartAgentRun operation middleware
func (siw *ServerInterfaceWrapper) StartAgentRun(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartAgentRun(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProviders operation middleware
func (siw *ServerInterfaceWrapper) ListProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProvider operation middleware
func (siw *ServerInterfaceWrapper) CreateProvider(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProvider(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProvider operation middleware
func (siw *ServerInterfaceWrapper) DeleteProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "providerName" -------------
	var providerName ProviderName

	err = runtime.BindStyledParameterWithOptions("simple", "providerName", r.PathValue("providerName"), &providerName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProvider(w, r, providerName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProvider operation middleware
func (siw *ServerInterfaceWrapper) GetProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "providerName" -------------
	var providerName ProviderName

	err = runtime.BindStyledParameterWithOptions("simple", "providerName", r.PathValue("providerName"), &providerName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProvider(w, r, providerName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProvider operation middleware
func (siw *ServerInterfaceWrapper) UpdateProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "providerName" -------------
	var providerName ProviderName

	err = runtime.BindStyledParameterWithOptions("simple", "providerName", r.PathValue("providerName"), &providerName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProvider(w, r, providerName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSessionsParams

	// ------------- Required query parameter "limit" -------------

	if paramValue := r.URL.Query().Get("limit"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReadSession operation middleware
func (siw *ServerInterfaceWrapper) ReadSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReadSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ContinueAgentRun operation middleware
func (siw *ServerInterfaceWrapper) ContinueAgentRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ContinueAgentRun(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/agent-profiles", wrapper.ListAgentProfiles)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/agent-profiles", wrapper.CreateAgentProfile)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/agent-profiles/{profileName}", wrapper.DeleteAgentProfile)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/agent-profiles/{profileName}", wrapper.GetAgentProfile)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/agent-profiles/{profileName}", wrapper.UpdateAgentProfile)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/agent-runs", wrapper.StartAgentRun)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/models", wrapper.ListModels)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/providers", wrapper.ListProviders)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/providers", wrapper.CreateProvider)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/providers/{providerName}", wrapper.DeleteProvider)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/providers/{providerName}", wrapper.GetProvider)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/providers/{providerName}", wrapper.UpdateProvider)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions", wrapper.ListSessions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/{sessionId}", wrapper.ReadSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions/{sessionId}/agent-runs", wrapper.ContinueAgentRun)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w97W4bt5avQsxeYOWsJNu9Tm9rY3+kTtp6mzSGFaPYrbIQNXMksZkhpyRHjhoI6Dvs",
	"/bOv1ydZHJLzzdGHLSfNvfsncDRD8vB88XxyPgShSFLBgWsVnH8IUippAhqk+d83jEeMz3+kCeB/I1Ch",
	"ZKlmggfnwS1nv2ZAXqfAL0UEZGpfJpwmQHqpZAmVK/IOVn0Cw/mQTEQKPBQRDBLK+ORoGPQDhhOlVC+C",
	"fsDNKsG0smY/kPBrxiREwbmWGfQDFS4goQhMwvhL4HO9CM5P+4FepThYacn4PFiv+8G1FDMWw0bYU/tO",
	"N8ihQFgGdA5cd0KcVlZ6IMRLFoHcBrJ5aTOaKZv07V9SZBrkJtjLNR8C/AiUYoJfRW3I3SPCIuCazRhI",
	"0jOg3t5ePT8iEnQmOURkJkVCKEklLJnIFJkoO/AbkfFoQoQk4UIo4GQmJKGEwx0JBV+CVBRX6tihKgC7",
	"//bWOFSlgiuwckGjG/g1A6Xxf6HgGrj5k6ZpzEIDznEqxTSG5N9+UYiFD5XF/iJhFpwH/3Jcyt6xfaqO",
	"r+2o56Api5Vdu47OVzSeCZlARKSFgUxFtEL0LGnMIrM4mVEWZxKGwbofXAo+i1n4KWC9ASUyGToJCx0g",
	"pBdldm1Axj0yUF5xDZLT+IWUQn4CUG85vE8h1BARBXIJkgBCYmD7UehvkQk/KQaFJjMEwkB0y2mmF0Ky",
	"3+BTQPUs0wsUZrsMyeUKmZBxw4YklGDkncZqaDSEmx0Xf3Z5PdIRE89Qr16KJKEWtzSKGE5I42spUpCa",
	"obzNaKygCYEbRSKY0SzWimQKIqIFiWnGwwWhnDy7vB7g7qhm0xiIwhWJUeWoKtLKCh8CKueqrbnyRaic",
	"ZwmiiKRUuXX0AjasQOA9hJmm0xiMXtKQqK16pviBSklXQT/IjM6/soNRZa37eF7n6PIDW65cQcdmaBHE",
	"bQq+1J0/FzC8LV4U018g1LgFQ1N3+OZ0fmFAYoKPQGvGLar3IPZNxjVLYCDu8JyAfLaS+HgieLeXn/DF",
	"GA/pG0y4STK8jItEufMQ5HVqt0fuhHyHllHEJIRayFWTWR11miRpsUciInDSjkdPQMN0YMYETYwVGCc4",
	"Zit+lGe5Bs3N2v06trbR30t3weH1LDj/eQumK9PcwDyLqWzPtu7vPkk3L67fNsB+yZS+cef9npyKQ4mY",
	"EUWXEDlVUMVxnfXyJ/h3oSJ2x4qDsKk3mpQrVtlGrk48P4K0TjMW6wHju0ioG/hKRBC3xezbLI5Xg18z",
	"GqNtWZwIhvFjwjiZ5EbusflpgLbIBIFItuq9UuQ2ideQvE6YNtuSFoXl9mrbAp4lSBH3VoUgHUJX2/l2",
	"8t2LZZ/5mJVQVRrm05XVUNdXbdqEEqiG6JluI+lq9Jp89eXJKTHvILKQLZSmSYrzIAEoarGIahjgI5/K",
	"i5hKY7ry+0TfZwnlg5lkwKN4VcAe0ynEpJfQFZkCgSTVqyOvPgUfp+8qfz51FDCutMxC/NljT7iRA5VC",
	"yGYsJFNY0CUzVlM5zgsq3+QUaggXnIU07vZo/QiQIoZOMAk+JfbRFM+vBZsvBjEsISbOHWJTFjO98s6t",
	"hYhvYOZBwxshcIYZSOAhKEKXlMW5waIXTOXbqJlOm42ldT/I0mgrK8ZU6YF9cX9ubAgntz5zlUMdRht8",
	"UMGFj+f6FSGq7qJT3m8yXnE/N4p6XVgTUIrOYRuX3yqQr+yrl86vWPdrYY4WgvFXPPdQT/jUyR167pWz",
	"QLnNkzsWxyilxiJCDWroLzO+r01aj8LkO+3E4UhLoMllxW3aXWMadUxEptMsd745UWZCiMjERosILBGp",
	"50TDe01SKrUiaJ6L3CqcIKtMUE2laR79ePb8B+ICFm780XDMJ2b0hFQVGrlbACeCxyuSgKYR1ZQYwQGF",
	"1uOYt40NnKRNuVc7T3pBRMIM2cjE+ZsTgi6ehHiF79E4FncQ2Vn0AiTgr1wYHFmQdrdyLIGuqdQ+We9U",
	"XFEWgsw50XHBRY45A38OIDrUCjTSDt/NeAQyXuHuDOar53WmQAbWFoi3H9oW0Vs478VyI9/Z+FTDwaNS",
	"MlSXRMUsNOKG/JKHyYZmygk5JhMD6PDly1e5STAhMwZxhGd6DEvKNWraMGaI9jHvGRa1DMz4vG+4ldGY",
	"hIuMv1N9gjSKAcE4GpKRiY4og1MaVRiaRYoIWXCOjwdt0MKrzaeS8nDhfVQJbuzINhW1ZaI4l14r7try",
	"dcGvTmepTM5oiCqM2xhQziIt6STH5OXLV/lhCH4bA2d4VSre9gs5JxReHULhm4pF3gkY1yBllmqoPp8K",
	"EQPl9oWlsJGaK/8Mjt6ec5OHEhLgmsbOnrZa78LizGhHo9UmaCpeWjaBCYq94WDLQfjfGUMWsQoeCL5d",
	"wVYF1uo8vt00ZM0ib4usGSWyt1EMc9w4OhCFarf8YVEwJC/e01DHqPzt0QfvdZ/gSX9J47iPomCPfYXe",
	"yGbdjGP9No6bbhvvv3HvPaealsYXrrzLSPumHbv24PLS2Cd1X2M3+6MZzKwErJEXrGfA56jT2laDxxPc",
	"5A0U8ZbFBrfgM/MDtninD/cKyFWSuGghnWmQhbO2w+oH9B62xUUP7EvsE4btMPv9hn6bk952ylOeOXVZ",
	"1oOLFG/lZh8W/MxnO0jwE0EtwLNhUK9o2kd2NrUrhC9rg3aXk84U9tEOPLqnfzQHDrIim1QpETJqzFOm",
	"F5Z3K3TbxxdyLFp3iWqkbiJ2O5danN6PSe1Ywjg6TApiCA2HWkQUCKg6R50MO91UklAwnZ05J6ddUcgh",
	"+cn4N9YL6BtizJhE6XFv5vZJDhOzeSUvZ26k96i2tQKAnbgoST0RDPTJiX2IUN5RGdkUQkOIyCwWdw/z",
	"nR0I3SyRFyoc3gjgcFdWOISCz9g8k7Qjb5OyH2DVxtSz6ysUWVslUMtTDslICwkR2nRpTNFufq9JLxYh",
	"jY8jWCKtd5H0KVVwKz3m8jdUAbm9eZlLerEVhAl4lAq2Q7Ktfz8zp9u8MZa7z/U3v1ePzIUU2XxRnJsG",
	"+OGubruZ7tIQzeey76iDfTbKq0xpklAdLsjkv3+mg9/e4j8ng68Hb5/8ZfIgG8b+4LFhLOFSKbQIRUzw",
	"vSF5zeNVXmFTSaYZh0dlaSqkhugB8Pj1uHmpZLt+zvo+CX0uOGyJLXhDgy0vNBJ8ewi02/2qMsO+rpf1",
	"NNtsSWs8eQDPwCUKYDgf9sk4+O76DTkbno6Doz1C8G8KznUJp0aVE048T/WgnHgLR6osSahkv1G7QJH+",
	"6kDXc1BszqkGZcXWQoHKrzYR0VS9U67wytoe9gx28QzNdAwK/YEZSbJYszQGO5ciC7oEOzlwJEjt6ETv",
	"19SlFIel8W+3+O0Gl518c8Vn4sFcQ0MpVKnGVJ8wHsaZOedrytloHETYrJFJzEkZdpxAB1bTh+Ivn01h",
	"drpBz+VaF2bsPR6PTVTYtfEtRWL2DvxJ1aPtZQQFLP0tPHCAJHzJC46RHUvQOC7Zok3W8rjc/dgzHLvN",
	"c3QT+7bs9a3223VhCIZbSqOeXV4/uACKqgFTeRlUsfIBip72r3CSWeno3reQqW/3v4kyzks/WG1I0zdX",
	"nb7O7qzYiijsWCFSLLQDAh5YZdAqF9+10OAgkYpqscJu9QcuuPHIcYltzmXreS3Xff/cdd3xw71uiRPs",
	"k6v27/qeSs3prlyntflDS8oVGuAej/DymhSP84odY8mbIriG9b6nCinX3Y6De8qOSyHgiebwUBUk26OQ",
	"p8w3Rkv2ZjMbCigTCZuSla29q2pLQAcH76/bLCZvzehdS98cf9dbS6qNAbV9lrBtp6iDYz96XlOJZ6ip",
	"+LRAHLuSFC5Ke9NWBDi+31Adl9JVLGh0YPLkfvFm5q/i0HmpOTg+3DUKy/fKft98e0m+Pnv6N+Jq2klk",
	"ZyE9lU0V6CNf3SC+0ZEzVZry0M/1SlOdVWuOGNcwB2nwgn7SRowV2jiTzKuHfWgxtugBbAt/8Mxfemrt",
	"350FsIz67V536pZ4u2HT97Yn/FvtsCdILw8LootM1TuIjrpCitcSlgzufKUyOI7kM6X2PedTT4bD4fv/",
	"/O10cjQkP8ISbCAZ/Sh82euXPTyO2DZX/kTlmDuXYX7u8cngoXFF3wSfqJqxI9aYy0SX/dff5NyOKn18",
	"B4lNVhsDfbhT3c2It8qFspjNQU6uX4/ekGM3Qh1/KMauj40lPJAZV5PhjqHQ6tobULGXpq8jI4d0Z73t",
	"lnzlyrJ8rK+F9lX/vMGfCc+SqS2py5e2ofg8jvZrBnJFelOYCQkkZgnTx2I2y4/k5hHqtyBskSxCsQFr",
	"xRb2w9g9vL4ttlFuA/j7XM3jIXkW39GVIlzwgS2u/OP3vxMJSsTL8mia0vAd8GhIvrMhWYjIklFTVVYP",
	"3/YYWv/131xAUJEojwFHR30SgWTLvKC0jNNmCmReEGmKkygxKEBJj8iMxjHCYgPHOZ3vmF6ITOPCNnFm",
	"t1YN8B7OJa3ZkgbD+zibDvkjY7odUsnYGb1MUpiJdT74aQF6AYhgmXEkT5hJCVzHK2L7XeYSlCqLnfP6",
	"zUrBKQ01W5rykiiG7RWnhe6xEHnxY6tOpRTyPtgJXQHl9upFU+/oPeXLGkif2SCBRuaQd63LFy53hiiy",
	"+QZbhmfqTlFkdtbIm2rBG8W4EUPAEsaptmWqCU1TnDsPQO1Qe/rCLWsSaB2vl1k6VyDaqbybZOvXD7/N",
	"Or9y4vYb/Lx5YFWM1gUvOLPPIXbd37GVrw3Mtr49LxQ7F//uuEYTs9sGlDQzDYO1isv9fBdTs1YW5eZ9",
	"/OWpYOu3O2P0uzvNzzoalzVC0PuP0esfiZWF6lFdSgeLOg3ikMYxuXpeNwW0LcZTWaz3yXDhqFnGTRGd",
	"sa+3yzaLNiWQGjWt94q2VZ1IandWkqxNGx+qLn04EpLNTS20mRLReGhUlZdV7McsZnLX1bKNN/Yihw2S",
	"PUL5sDEJusuHycS2eqK1X1Zk8Mi0ftAwhBRlbgFy30rj7/9pCow/rxJfcgNpTENTCgEE3jNluCNmSh+s",
	"/Pchdb9WEB6n7reQhZzRW5k22wL0EWuAf/r0pb8N4u1dA2spduCCx4ra6ih2zDWXba1ZpfinhP212H1q",
	"JE0vuxbkHUBq5Mi5L2RJ4wweKZD5kILI7z9SHeSu2uXeMchmVt5h1cuX7Rbd/ZjythIOqAbCKjEvcoxc",
	"qRnPAD3ZWidrj9rohokqoEq8cP2UXKPB5FoLj/bpQ82UNutRxgnVJAbqqsvyTixTFl+GUww01ke0FzYN",
	"FIugcgnWhWtqRQIpIz8SfrE3POGGzX6nImKg9uhNrSDe35u6czNoc6b96DdifI6cajo3y1Y1WovzkF71",
	"ijBPwqOj76yZ4sa32ltYGzPEVuo1JPLNm2sj4ka/GJsMOcpGu8q0zPMfyCRvaOcgTevqTcYnpoYdd5MX",
	"NGYm6PRmYfiQg8RNKjIZ5R2rKFWj0YvJBTErF3e14XvkyRPbsToYIRzGg1NPnpDeBLd1bHzZgQ0tTJBf",
	"x/zJEzux4UZJQ33+5Al5QcMFGY1eFKg1IChNeURlRGbSAEJ6EzPh+aRoZeiTSUQ1PZ8QNKlxhRdLkCv7",
	"64TEjJs2A0oqFrdldcqJnW1CanEJ0lMA+e5t028JOJWaLFUhuAi6R7KnMGdcuYJ7Fxi4sEEWe/cZVYrN",
	"eXkH31U0GXNTe5UwrQjTljx5cLFxVZ9toN41tj7mObTKtNzmijUvTe0pmkD9sju1oClcFG+EIgFVBjxT",
	"qhdO9bhQbTBCUiQiKrlRs8RkBoN+sASpLOOeDE+HJyaykQKnKQvOg7+an/rmVkEjMw706t09czBShJJV",
	"tNmalGzVjFdB4xbBL05ONlzdtt+VbZ3XF3kub9t8R9G6H5ydnHatV2zguHYD3bofPLW72Tyofsnfuqh2",
	"XuVgocfsgwtJSdFt+tk29pYP3q77QSqUhwDtrlV3BSQo/Y2IVgdDfnd77LquSt0Vbg0uOH0ULtjEATUU",
	"Ehdkd6TfgYqV6y/vyy1nJ19vH1RcXHkI9rJEylVem8U2cdi635T64w+V0qK1PQHzlvU6Fz43vze4sHrN",
	"bkf0tHzluHqV7fpti3/OPPZ9jcAWtGj4AGqdbR9UXJJ5CGpZrPnjOmg/5Nnqbp3g1cnfgX5MSpx8Wkn+",
	"nAj8HeiHUDfNPNRtxxkPQODDHxfd4dCdjouPz2QW4NblDB/1uPjY/Gn3XATT3PU59ubpe58eaO4aF9jZ",
	"K410gTmhGlZ533pO5e00rjkcyJwtgTfS+mihW19GufujiEBzfjR64Rwoa9hDVLXsCU1ToFJtt+nzN+wa",
	"1sSuy6DxQHKn7pHsreYlaPcSm5b3Z4oA3tMkdUa9Mn/iXybwlec9z0kVL2NunDvyYWyfjoPzcS1DOw76",
	"47K0wTx++vQEvjo7ORnAF19PB2en0dmA/u30y8HZ2ZdfPn16dnZycnIyDtbo0bkVDeW9S9knuIa7w2fs",
	"cjvjfK/j4PyDfarGqAHHZudm8PcQx2IcrN+u77+YDU6Ma/f27A1Dn9wJGUfDFiyR4OAFxTxAHFWulvbk",
	"Kt98O/jKeO2OYa0bb6b54/f/VbkTbqQbvXDjgxfpupqLPebG7c45xIhayZtH3qKYtiotYTHl/PaqaCuo",
	"6JLGRrpkxvMrt8BcqWVKBEzkfgE0L9p1cb/BG1dpWEWCaxhtM/kFCRdUKtD/nunZ4CsfyB9RrT9YS9t4",
	"h1WYhWff0sVG7Vo9XIaAnX3YDNUjH9sOQdczmAfmUeP72gcdS3EtV67B1AWIa/2lY66FvR+PmEIZkzpy",
	"GeHuXkvS87dZNuJqPj2M3rSNaz9m2KHdqbkh3tBsx/wzxBp2ahGtMJRDqWWmWg19ZwzoujLNoxHC20Kw",
	"gRadfQKfniQdoFWIUGJ0W/Dnuuw2frzATzM7+JGDPu2+jDbZr/29Ev+EkR8/d3UwV03ITcin+FjODjGf",
	"CvPt7YSWH+XZLeDTQeDPOfLT0d/TDg/U1UFX3OfRqHHyJ5Dkzy/yc0/qboj7HJLAjxX0uddR8XEZLA/2",
	"pJsY7R886nNP9sTjotqes9HFyHOXxUXbPRb1bYNFv2zmUs7Wj+OiK2PMpxALPjfugy3nrZTwQGRCQn2i",
	"TDc7QhxTpUmlS4z0EqE0kRCiA2GCPUddLsSobM9pCFWzNfI9S7LE1yykhaulJb3TP37/n9OTk/JjdKZ3",
	"qPxWm2ke2vydNrtOcH56cmKqhtz/fH1GrTsYvbCpdywlPURySueMU3fL9fP88hQtyEkXvLbNKej7fO8q",
	"eCce8B7zIPF1mfnOErthiEyJTAUx5R3ewecUDTAuREHb/C7HtnBUxLfg77r0VksVNkhyGtOV9RUXTGkh",
	"TYNo/f5+QpUJQM1QeJS5XsvTF2T7fXKQx7wI/lb6XpTGxUQK3MWe8poJdx2krUVbwpZ40nDMr9w9pPl3",
	"GRVhkdE65WLAI+WqUMgkEhzyALAtuJJm67bkFze+MvUnrmxGyAjk+ZifDv0x5J7RqTJRdSiiozH/ohxi",
	"mz+KMROLIvMZyAmCOzka878OyX+BFObWeSGh8ekFB2XeCucgHfMzSwUz33kFj2a7BoONeeqYnDHO1ALU",
	"mD8d1nDjUaE3QCPHYnubJeUXNXfQFd5o9n3Cov+6V1B0/6hnyTl1Obmo8jerCIml05889nn2Cb7BmLeb",
	"1j8M+WAliizb1GE9S7VchGpX9cYrgiBawZEZP9oUft1SCtadGxsZhWRd+FqFo0tI2WRYDnY1DVZmzvL9",
	"V1Nio1ZpGVVkoqpJrMlFLVfGFNH0HfB6uRnpFV+vZUKOuVfxmeShLY0duE/Zos0XQQq2Qt98GMfU36Ui",
	"ZuHKa5ZdOoVVSbI9TLH8wyXoHildNsokkD9+//vDs1T/nya6jx/40b+86xoAzfeQ2KxaHuuKzE2mh+qa",
	"HWPKVxVx1yHIjHPG52h0IaHMp1S0dT1woKuid7cClLZrbw56IOTABmiPTM+zMH0Z5utY+fdmxvwwAdK8",
	"yp/yMqtk/c52OW6nejfXJphPA3n8wxuIqTFxncdq6rQdMqeuSSToB5mMg/Pg2Cgmt0rrJDApPyHL3gRr",
	"KqDOR5cWF/F+sKV02ypwt71Em4fgEWFcpRBqlITSqygnKTyH9hSvKMej6eXLV13JDNK7vLl9flTOVoYR",
	"Oqfz1UptmbVRitK12Q05sEr2s5oOc/O7bNj67fr/AgAA///WxJnhSIAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
